### ISSUE TITLE
feat: support gptneox and falcon to the llama.cpp backend

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#1009]
Falcon and gptneox seems to be supported in llama.cpp with a separate example - would be really cool to merge it in the binding and make it transparent for the user (to either load falcon, or gptneox depending on the model): https://github.com/ggerganov/llama.cpp/tree/master/examples/gptneox-wip

**Comment by yugeeklab** [comment]
Hi there! I've been following your project with great interest, and I'd love to contribute by tackling this issue. Is it okay if I take it on?

**Comment by mudler** [comment]
Sure thing, please go ahead!

**Comment by mudler** [comment]
this should be already working - closing for now
