### ISSUE TITLE
feat(transformer): transformer-based backend

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#1015]
**Is your feature request related to a problem? Please describe.**
It makes sense to have a backend which is tied to https://github.com/huggingface/transformers. This would increase the range of support for LLM that LocalAI already offers

**Describe the solution you'd like**
Ideally would be preferred to use a wrapper around transformers and xformers to avoid duplicating efforts. 

**Describe alternatives you've considered**

**Additional context**

**Comment by yhyu13** [comment]
Is Vllm fully integrated? vLLM begins to seem to be many AWQ quantized model's first choice recently

**Comment by mudler** [comment]
> Is Vllm fully integrated? vLLM begins to seem to be many AWQ quantized model's first choice recently

yep, going into the next release soon!
