### ISSUE TITLE
feat: tortoiseTTS

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#1016]
**Is your feature request related to a problem? Please describe.**
We support rhaspy, bark and now vall-e-x (#1007). Another popular project is https://github.com/neonbjb/tortoise-tts

**Describe the solution you'd like**
A backend for tortoise tts

**Describe alternatives you've considered**

**Additional context**
Having support for tortoiseTTS too would help not only for users already using it, but allows also LocalAI to be a good benchmarking platform for all the solutions out there.

**Comment by mudler** [comment]
Also relevant: https://twitter.com/reach_vb/status/1702369875820212608?t=C96cnC9AF5O59bHJ-kIdyw&s=19

Looks like coqui brings tortoiseTTS on par with vall-e-x voice cloning capabilities. Maybe worth putting effort directly into that one.

**Comment by djmaze** [comment]
The recently released [XTTS-v2](https://huggingface.co/coqui/XTTS-v2) is even more exciting.

**Comment by balisujohn** [comment]
I have started work on tortoise.cpp, which might be of interest https://github.com/balisujohn/tortoise.cpp

**Comment by mudler** [comment]
https://github.com/mudler/LocalAI/pull/1489
