### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by BodhiHu** [mudler/LocalAI#1028]
**Is your feature request related to a problem? Please describe.**

Hello, I tried `ollama` on my macbook and got pretty good performance compared to running `LocalAI` with `llama-stable` directly(which consumes lots of CPU and not using GPU at all):

<img width="430" alt="Screenshot 2023-08-24 at 18 07 54" src="https://github.com/go-skynet/LocalAI/assets/3882561/37afafdd-3570-4e31-9ce8-52e94786b60d">

While `Ollama` will use the GPU and so saves CPU, but unfortunately `ollama` did not have OpenAI like API.

**Describe the solution you'd like**
Add support for ollama.

**Describe alternatives you've considered**

Had not found one proper.

**Additional context**

Thanks a lot :D

**Comment by mudler** [comment]
While I can understand the request of another backend, ollama isn't really adding any features that LocalAI hasn't already.

Did you followed the docs to use GPU? https://localai.io/basics/getting_started/#cuda

Ollama isn't in the roadmap, however feel free to take a stab at it.

**Comment by mudler** [comment]
come up again, up for grabs :)
