### ISSUE TITLE
No docker windows

### ISSUE THREAD

**Issue by TomiLikesToCode** [mudler/LocalAI#1036]
Can you release a version for windows that does not require docker? Docker is unstable and glithcy and it eats 6 gigs of ram while no image is running

**Comment by EchedeyLR** [comment]
What happens if you just run docker engine on top of WSL if you have it around?

I don't remember exactly if Docker in Windows used WSL directly or not, but Docker is not Windows designed, it requires virtualization to be able to run.

**Comment by EchedeyLR** [comment]
Other option is build LocalAI yourself too.

**Comment by TomiLikesToCode** [comment]
> Other option is build LocalAI yourself too.

But its for linux and mac not for windows

**Comment by EchedeyLR** [comment]
> But its for linux and mac not for windows

WSL??

**Comment by TomiLikesToCode** [comment]
but wsl is using too much ram

**Comment by EchedeyLR** [comment]
A default installation of WSL is using too much for you even with hardware virtualization enabled?

Are you sure is not that it shows as dedicated RAM for it? Do a `free -h` inside a default WSL installation.
