### ISSUE TITLE
feat(exllama2): Add support to exllama2

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#1053]
exllama2 has just been released: https://github.com/turboderp/exllamav2

This card is a tracker to add it to LocalAI, similarly to exllama

**Comment by Aisuko** [comment]
We already have the example of exllama. I will try this one.

**Comment by Aisuko** [comment]
ExLlama2 needs CUDA 117 or 118. I have been tried to install it on older coda, but it cannot work well. So, this one maybe need to work on these two environment.
