### ISSUE TITLE
feat: add support for GPTQ-for-LLaMa

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#1055]
Tracker to add support to https://github.com/qwopqwop200/GPTQ-for-LLaMa

**Comment by Aisuko** [comment]
According to the README.md of the project, it only support AutoGPTQ. We already have a AutoGPTQ backend but it still need to be test.

**Comment by mudler** [comment]
yes, this became less relevant as now the author focuses on AutoGPTQ. Closing
