### ISSUE TITLE
enhancement: use separate conda env for extra grpc backends

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#1117]
**Is your feature request related to a problem? Please describe.**
Python requirements my be conflicting 

**Describe the solution you'd like**
Create a separate conda environment for each backend and use a customized entrypoint.

**Describe alternatives you've considered**
Just rely on external

**Additional context**
N/A

**Comment by Aisuko** [comment]
Hi @mudler. I have an idea in here. As you mentioned `separate conda environment for each backend`. We will create a `conda_env_requirement.yml`  in each folder. And it should include all the dependencies of the backend, right?  Shall we create a Makefile in `extra` folder to create `conda` env for every external `grpc` service ? Or create Makefile for every external gRPC backend?

The Makefile format should be like:

```
.PONY: diffusers
diffusers:
	@echo "Creating virtual environment..."
	@conda env create --name <backend-name> --file xxx.yml
	@echo "Virtual environment created."
```

**Comment by Aisuko** [comment]
- [ ] AutoGPTQ @Aisuko https://github.com/go-skynet/LocalAI/pull/1137/commits/5f55398d86a3729899a263169062d78b92a1e3a2
- [ ] bark
- [ ] diffusers
- [ ] exllama
- [ ] huggingface
- [ ] vall-e-x
- [ ] vllm

**Comment by mudler** [comment]
> Hi @mudler. I have an idea in here. As you mentioned `separate conda environment for each backend`. We will create a `conda_env_requirement.yml` in each folder. And it should include all the dependencies of the backend, right? Shall we create a Makefile in `extra` folder to create `conda` env for every external `grpc` service ? Or create Makefile for every external gRPC backend?
> 
> The Makefile format should be like:
> 
> ```
> .PONY: <backend-name>
> <backend-name>:
> 	@echo "Creating virtual environment..."
> 	@conda env create --name <backend-name> --file xxx.yml
> 	@echo "Virtual environment created."
> ```

that sounds good, we just need as well to have a top-level target that prepares the envs for all the extra backends, and a wrapper script to run the backend with the environment to use for LocalAI

**Comment by mudler** [comment]
see https://github.com/go-skynet/LocalAI/pull/1144/commits/fbbd2f6a35734d9e40d289fcfdfdbc2db42e2771 for an example for bark/autogptq (not tested yet)
