### ISSUE TITLE
Request: exposing `REBUILD` as an `ARG` in `Dockerfile`

### ISSUE THREAD

**Issue by jamesbraza** [mudler/LocalAI#1125]
It would be convenient to expose `REBUILD` as an `ARG` in the `Dockerfile` for local toying around.

That way, `docker buildx build` can pass `--build-arg REBUILD=true`, without having to directly edit the `Dockerfile`'s source.

**Comment by rai62** [comment]
When looking at the Dockerfile, it seems that `REBUILD` is only used in `entrypoint.sh`.
ENTRYPOINT is executed during `docker run` and not during `docker build`.

I think it is possible to rebuild with the following command.
```
docker run --env REBUILD=true localai
```
or like env in docker-compose.yaml
```
docker run --env-file ./.env localai
```

**Comment by jamesbraza** [comment]
That is a good point @rai62 , thanks for sharing. I will try to make a docs PR for that info shortly

**Comment by jamesbraza** [comment]
Opened a PR adding that info to https://localai.io/advanced/index.html 🦾
