### ISSUE TITLE
feat: allow parallel requests for same model

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#1142]
**Is your feature request related to a problem? Please describe.**
Currently each model gets an instance only

**Describe the solution you'd like**
A flag or a YAML config option to tell the maximum number of instance to spawn/connect to. defaults to 1 (mimicking the current behavior)

**Describe alternatives you've considered**

**Additional context**
Ideally we should keep track of what models are being used and redirect to free slots.
Also we need to keep into account the logic which is already in place to handle a single GPU device (1 model loaded only)

Related: https://github.com/go-skynet/go-llama.cpp/issues/253

**Comment by ACiDGRiM** [comment]
I'm a fan of this, especially with the potential of localagi 

I want to run two gpu LLMs on different servers i run, currently i just load balance round robbin between distinct local ai front-backends.

Ideally, one api front end could queue incoming requests and send to the next available llm. Allowing all LLM in a pool to store and retrieve from long term memory would be awesome

**Comment by mudler** [comment]
this is actually already possible with llama.cpp and by specifying PARALLEL_REQUESTS or --parallel-requests and the number of parallel requests for llama.cpp https://github.com/mudler/LocalAI/blob/d6073ac18ec9265b733685ff8c12ab829ed81dec/.env#L72. Other backends like vllm should also support this natively
