### ISSUE TITLE
TheBloke's future models won't work with LocalAI

### ISSUE THREAD

**Issue by no-skynet** [mudler/LocalAI#1163]
Having found models from TheBloke to be particular well documented and easy to work with, I have basically stopped looking at any other. I even built my own TheBloke filtered gallery. 

This seemed to work well, for a while at least. However, The Bloke recently switched to using ChatML for all future models.

See here: 
https://www.google.com/search?hl=en&q=%22All%20of%20my%20future%20models%20will%20use%20ChatML%20prompt%20format%22
"All of my future models will use ChatML prompt format" - TheBloke

...

_Originally posted by @no-skynet in https://github.com/go-skynet/LocalAI/issues/67#issuecomment-1758096188_

**Comment by no-skynet** [comment]
So we can build a ChatML template that will work with [OpenAI's Chat Markup Language (ChatML)](https://github.com/openai/openai-python/blob/main/chatml.md) format, with <|im_start|> and <|im_end|> tokens?

**Comment by mudler** [comment]
> So we can build a ChatML template that will work with [OpenAI's Chat Markup Language (ChatML)](https://github.com/openai/openai-python/blob/main/chatml.md) format, with <|im_start|> and <|im_end|> tokens?

yes definetly!

**Comment by mudler** [comment]
so if I'm reading correctly a chat template might be look like this, but note, I've didn't tried it yet:

```
<|im_start|>{{if eq .RoleName "assistant"}}system name=example_assistant{{else if eq .RoleName "system"}}system{{end}}
{{if .Content}}{{.Content}}{{end}}
<|im_end|>
```

**Comment by lunamidori5** [comment]
> so if I'm reading correctly a chat template might be look like this, but note, I've didn't tried it yet:
> 
> ```
> <|im_start|>{{if eq .RoleName "assistant"}}assistant{{else if eq .RoleName "system"}}system{{else if eq .RoleName "user"}}user{{end}}
> {{if .Content}}{{.Content}}{{end}}
> <|im_end|>
> ```

GGUF does this auto, it would be use the one on the demo page if using a GGUF model, love the new meta data in the model <3

**Comment by mudler** [comment]
> > so if I'm reading correctly a chat template might be look like this, but note, I've didn't tried it yet:
> > ```
> > <|im_start|>{{if eq .RoleName "assistant"}}assistant{{else if eq .RoleName "system"}}system{{else if eq .RoleName "user"}}user{{end}}
> > {{if .Content}}{{.Content}}{{end}}
> > <|im_end|>
> > ```
> 
> GGUF does this auto, it would be use the one on the demo page if using a GGUF model, love the new meta data in the model 

this is just for chat models and not instructors for what I can see - I doubt the prompt is injected inside the model file

**Comment by dave-gray101** [comment]
good to know about this, I'm in the process of improving the model gallery scraper right now, and I'll add this to the list of things to test for

**Comment by no-skynet** [comment]
@dave-gray101, aother thing to look out for... the last time I checked out the scraper, it seemed to be downloading *.bin files only, however _TheBloke_ has switched to *.gguf files. In my own gallery scraper I added support for both and found an extra 400+ new models from _TheBloke_ :sweat_smile:

**Comment by scenaristeur** [comment]
ggml seems deprecated on TheBloke models , (https://huggingface.co/TheBloke/CodeLlama-13B-Instruct-GGML)
![image](https://github.com/go-skynet/LocalAI/assets/4020744/e72645f1-ed2a-4535-82ad-f759e83c78cf)
