### ISSUE TITLE
Allow grpc backend services to exit after idling for a while

### ISSUE THREAD

**Issue by garloff** [mudler/LocalAI#1202]
**Is your feature request related to a problem? Please describe.**

I have successfully built LocalAI to work with AMD ROCm hipBLAS, working nicely on RX7900XTX.
The card eats ~14W when idling, ~53W when the shaders are clocked to 2.45GHz and ~230W when doing LLM work with llama (at 2.45GHz shader speed and full mem speed 1.25GHz).

After sending the first request to LocalAI, llama keeps running and keeps /dev/kfd and /dev/dri/renderD128 open.
While the memory is clocked down, the shader clock remains at max and the card eats 53W.

**Describe the solution you'd like**
I would like llama to exit after idling for a while (minutes), so power consumption goes down. The fact that the model needs to be reloaded again from the disk to the VRAM is a price I'm happy to pay for the saved power.

**Describe alternatives you've considered**
Alternatives:
* The backend llama service could do something clever with closing the compute device and reopening it again. This seems to be more complex though.
* The amdgpu kernel driver could do some magic, allowing the shader clock to go down after not receiving compute commands for a while. This seems complex to me as well.

** Additional context **
If wanted, I can prepare a blog article how I got the rocm support working well (in the localai docker container on a Ubu2204 VM).

**Comment by mudler** [comment]
hey :wave: this should be fixed by https://github.com/mudler/LocalAI/pull/1341 which introduces a watchdog - I've extended it to watch also for idle times too

**Comment by garloff** [comment]
Hi Ettore,

Thanks for taking care of this! 
Will save some CO2 for the world and I can probably retire my little python script (at least for local-ai) that does something similar...
I'll let you know what my testing says.
