### ISSUE TITLE
Openai Python API changes

### ISSUE THREAD

**Issue by lunamidori5** [mudler/LocalAI#1223]
**Is your feature request related to a problem? Please describe.**
Yes, openai is changing the way their python pip is going to work, and want to make sure the devs know about it

**Describe the solution you'd like**
A reply to this would be nice

**Describe alternatives you've considered**
There is no way to do a alternative as this is out of my power

**Additional context**
https://github.com/openai/openai-python/discussions/631

**Comment by mudler** [comment]
thanks @lunamidori5 to bring this to my attention, at a glance it looks mostly just few changes on style, nevertheless examples should be updated once that gets in

**Comment by lunamidori5** [comment]
@mudler Ill get them updated and have a waiting PR for when the changes to openai are live, is that okay?

**Comment by lunamidori5** [comment]
@mudler looks like Localai will need updated to support the new backend - 
```
2023-10-27 22:04:56 INFO     discord_bot root ::= ("Pretoken_Profiles" | "Dream_API")
An error occurred: Error code: 500 - {'error': {'code': 500, 'message': 'failed reading parameters from request:json: cannot unmarshal string into Go struct field OpenAIRequest.functions of type []grammar.Function', 'type': ''}}
Retrying... Retry count: 1
```

**Comment by mudler** [comment]
> @mudler Ill get them updated and have a waiting PR for when the changes to openai are live, is that okay?

sounds good

> @mudler looks like Localai will need updated to support the new backend -
> 
> ```
> 2023-10-27 22:04:56 INFO     discord_bot root ::= ("Pretoken_Profiles" | "Dream_API")
> An error occurred: Error code: 500 - {'error': {'code': 500, 'message': 'failed reading parameters from request:json: cannot unmarshal string into Go struct field OpenAIRequest.functions of type []grammar.Function', 'type': ''}}
> Retrying... Retry count: 1
> ```

Can you try to get more logs out of it? also, what are the LocalAI logs?

**Comment by lunamidori5** [comment]
@mudler Ill get around to that ASAP!

**Comment by lunamidori5** [comment]
> thanks @lunamidori5 to bring this to my attention, I totally missed it! at a glance it looks mostly just few changes on style, nevertheless examples should be updated once that gets in

@mudler how tos have been updated and a few other things! Closing this now!
