### ISSUE TITLE
localAI slow response in kubernetes cluster.  (v1.24)

### ISSUE THREAD

**Issue by harshsing2891** [mudler/LocalAI#1234]
Hi Team
I have deployed localai  with the latest image using helm template  in kubernetes cluster. I have tried with no of models but for every model i am getting very delayed response  ( response time is between 1 minute to 4 minute). Please find below values.yaml file i have used  while deploying localai using helm. Please suggest how i can get fast response from localai

cat <<EOF > values.yaml
replicaCount: 1

deployment:
  image: quay.io/go-skynet/local-ai:latest
  env:
    threads: 4
    context_size: 512
  modelsPath: "/models"

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Prompt templates to include
# Note: the keys of this map will be the names of the prompt template files
promptTemplates:
  ggml-gpt4all-j.tmpl: |
    The prompt below is a question to answer, a task to complete, or a conversation to respond to; decide which and write an appropriate response.
    ### Prompt:
    {{.Input}}
    ### Response:

# Models to download at runtime
models:
  # Whether to force download models even if they already exist
  forceDownload: false

  # The list of URLs to download models from
  # Note: the name of the file will be the name of the loaded model
  list:
    - url: "https://gpt4all.io/models/ggml-gpt4all-j.bin"
      # basicAuth: base64EncodedCredentials

  # Persistent storage for models and prompt templates.
  # PVC and HostPath are mutually exclusive. If both are enabled,
  # PVC configuration takes precedence. If neither are enabled, ephemeral
  # storage is used.
  persistence:
    pvc:
      enabled: false
      size: 6Gi
      accessModes:
        - ReadWriteOnce

      annotations: {}

      # Optional
      storageClass: ~

    hostPath:
      enabled: false
      path: "/models"

service:
  type: ClusterIP
  port: 80
  annotations: {}
  # If using an AWS load balancer, you'll need to override the default 60s load balancer idle timeout
  # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1200"

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}

**Comment by lunamidori5** [comment]
@harshsing2891 I can not read your issues, can you please use codeblocks to format it into a readable way?

**Comment by harshsing2891** [comment]
Please find below content of values.yaml of helm template I am using for local ai deployment

replicaCount: 1

deployment:
image: quay.io/go-skynet/local-ai:latest
env:
threads: 4
context_size: 512
modelsPath: "/models"

resources:
{}

promptTemplates:
ggml-gpt4all-j.tmpl: |
The prompt below is a question to answer, a task to complete, or a conversation to respond to; decide which and write an appropriate response.
### Prompt:
{{.Input}}
### Response:

models:
 forceDownload: false 
 list:
   - url: "https://gpt4all.io/models/ggml-gpt4all-j.bin"

**Comment by harshsing2891** [comment]
Hi Mudler/Localai

I have added comments.please help

**Comment by lunamidori5** [comment]
@harshsing2891 Looks like you are running on CPU only, that is about 25x slower than running on GPU, it also looks like your running on a ``GGML`` model, that is a bit outdated and really slow due to ``llama`` no longer supporting it, if you would be willing please set up a ``GGUF`` based model by following the how to on the site. - https://localai.io/howtos/easy-model-import-downloaded/

**Comment by harshsing2891** [comment]
How to run on GPU in kubernetes cluster using helm template.please help

**Comment by harshsing2891** [comment]
How to enable GPU in localai helm template so it can be deployed in
kubernetes cluster .please help

THANKS AND REGARDS
  HARSH SINGH

**Comment by lunamidori5** [comment]
3x issue on same topic, closing this one
