### ISSUE TITLE
llama.cpp patch

### ISSUE THREAD

**Issue by JeremyBickel** [mudler/LocalAI#1245]
I'm sorry for this non-standard bug report. I can't find the file in question in the directory structure here, but the file stands out enough that I think this report will be useful to someone. There's a patch that's done in go-llama and go-llama-stable that causes a build failure because the patch file itself seems to be wrong. I don't know much about them, but it refers to two different files (common.cpp and common.h), and it tries to apply the patch for both these files - it applies it all on common.cpp. It caused me hours of rebuilding over and over to trace it down. So, just separate it into two patches or manually apply it - it's not very complex. NOTE: It applies to different files between the two go* branches. In llama, it's the "common" files located from the main directory, but in llama-stable, it's in the "common" files located from the examples directory.

I hope this helps someone.

**Comment by blob42** [comment]
Hi, are you doing a parallel compile ? Try compiling with a single job it should solve the issue

**Comment by JeremyBickel** [comment]
@blob42 No, it wasn't a parallel compile. I appreciate the attempt to help, but I didn't leave you enough information. At the time, I thought it would be *obvious*, so I didn't leave all the details. Now, I barely remember this. Given the date of this report and the fact that it had to do with a patch, It's probably taken care of. If someone recognizes the issue in the future, feel free to reopen this, even though I didn't give enough information about it - it *might* help? Thanks again, b.
