### ISSUE TITLE
call multiple functions in one message

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#1275]
https://platform.openai.com/docs/guides/function-calling/parallel-function-calling

From an implementation perspective, we need to force when generating the BNF to return an array instead of a single object, for instance:

```
root   ::= arr
value  ::= object | array | string | number | ("true" | "false" | "null") ws

arr  ::=
  "[\n" ws (
            value
    (",\n" ws value)*
  )? "]"
```

however, I'd probably mark this feature behind a flag (for either disabling or enabling it, depending on how well it behaves)

**Comment by elvisisvan** [comment]
this gon be fun

**Comment by mudler** [comment]
Initial PR in : https://github.com/mudler/LocalAI/pull/1726
