### ISSUE TITLE
Feat: support jina-embeddings via sentence-transformers

### ISSUE THREAD

**Issue by kno10** [mudler/LocalAI#1278]
Jina Embeddings are a promising current model for embeddings used in RAG.
https://huggingface.co/jinaai/jina-embeddings-v2-base-en
While they are available via huggingface transformers, the current localai backend will not load them:

`"could not load model (no success): Unexpected err=ValueError('The repository for /root/.cache/torch/sentence_transformers/jinaai_jina-embeddings-v2-base-en/ contains custom code which must be executed to correctlyload the model. You can inspect the repository content at https://hf.co//root/.cache/torch/sentence_transformers/jinaai_jina-embeddings-v2-base-en/.\\nPlease pass the argument 'trust_remote_code=True' to allow custom code to be run.'), type(err)=\u003cclass 'ValueError'\u003e","type":""}}`

As little work may be necessary as allowing to pass this option to the constructor.

**Comment by mudler** [comment]
this is covered by https://github.com/mudler/LocalAI/pull/1250

**Comment by mudler** [comment]
Still not ready

**Comment by kno10** [comment]
I still get the error
```js
{"error":{"code":500,"message":"could not load model (no success): Unexpected err=ValueError('The
repository for /root/.cache/torch/sentence_transformers/jinaai_jina-embeddings-v2-base-en/ contains
custom code which must be executed to correctly load the model. You can inspect the repository
content at https://hf.co//root/.cache/torch/sentence_transformers/jinaai_jina-embeddings-v2-base-en/.\\n
Please pass the argument `trust_remote_code=True`
to allow custom code to be run.'), type(err)=\u003cclass 'ValueError'\u003e","type":""}}
```
with master-cublas-cuda12  sha256:6ac4da5208e7

**Comment by kno10** [comment]
I noticed the following:
- #1308 added `trust_remote_code` to the `transformers` backend only, but not the `sentencetransformers`, but the pull request description mentioned renaming `huggingface-embeddings` to `sentencetransformers`
- I tried `transformers`, but that fails loading with `ImportError: cannot import name 'AutoModel' from partially initialized module 'transformers' (most likely due to a circular import) (/build/backend/python/transformers/transformers.py)`
  which likely is caused because the backend is in a file named `transformers.py`, trying to import from the huggingface package of the same name (hence circular import).

**Comment by kno10** [comment]
Thank you, it now works with the fixed `transformers` backend. While it was not loaded into the GPU, the CPU performance seems to be well usable for my current purpose.

**Comment by FrankDaze** [comment]
@kno10 could you describe how you got it to work? I pulled the latest cuda12 master image and made a rebuild. My yml file looks like this:

```. 
name: jina_de
backend: sentencetransformers
embeddings: true
parameters:
  model: Xenova/jina-embeddings-v2-base-de

**Comment by Ar9av** [comment]
Any updates on this?
