### ISSUE TITLE
Failing to get a response!

### ISSUE THREAD

**Issue by arbianqx** [mudler/LocalAI#1281]
**LocalAI version:**
v1.40.0-cublas-cuda11

**Environment, CPU architecture, OS, and Version:**
Linux pop-os 6.0.12-76060012-generic #202212290932~1674066459~20.04~3cd2bf3-Ubuntu SMP PREEMPT_DYNAMI x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
I have installed successfully a model, by running:
curl http://localhost:8080/models/apply -H "Content-Type: application/json" -d '{
     "id": "huggingface@TheBloke/Yarn-Mistral-7B-128k-GGUF/yarn-mistral-7b-128k.Q5_K_M.gguf"
   }'
   
After that it just keeps hanging and no response was comming:
curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "thebloke__yarn-mistral-7b-128k-gguf__yarn-mistral-7b-128k.q5_k_m.gguf",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.1
   }'

**To Reproduce**
Run docker container as follows:
docker run -d --rm \
  --name api \
  --gpus '"device=1"' \
  -p 8080:8080 \
  --env-file .env \
  -v $(pwd)/models:/models \
  -v $(pwd)/images:/tmp/generated/images \
  quay.io/go-skynet/local-ai:v1.40.0-cublas-cuda11 \
  /usr/bin/local-ai

**Expected behavior**
I'm expecting to get a response, but nothing is happening.

**Logs**
[logs.txt](https://github.com/mudler/LocalAI/files/13327836/logs.txt)

**Additional context**
Here is my .env:
GALLERIES=[{"name":"model-gallery", "url":"github:go-skynet/model-gallery/index.yaml"}, {"url": "github:go-skynet/model-gallery/huggingface.yaml","name":"huggingface"}]

MODELS_PATH=/models

DEBUG=true

BUILD_TYPE=cublas

I have also tried running without GPU, but the same keeps happening. Any idea on this?

**Comment by Aisuko** [comment]
Hi @arbianqx, according to the log. I believe the CPU acceleration was failed

```
11:16AM DBG GRPC(yarn-mistral-7b-128k.Q5_K_M.gguf-127.0.0.1:39895): stderr llm_load_tensors: using CUDA for GPU acceleration
11:16AM DBG GRPC(yarn-mistral-7b-128k.Q5_K_M.gguf-127.0.0.1:39895): stderr llm_load_tensors: mem required  = 4893.09 MB
11:16AM DBG GRPC(yarn-mistral-7b-128k.Q5_K_M.gguf-127.0.0.1:39895): stderr llm_load_tensors: offloading 0 repeating layers to GPU
11:16AM DBG GRPC(yarn-mistral-7b-128k.Q5_K_M.gguf-127.0.0.1:39895): stderr llm_load_tensors: offloaded 0/35 layers to GPU
11:16AM DBG GRPC(yarn-mistral-7b-128k.Q5_K_M.gguf-127.0.0.1:39895): stderr llm_load_tensors: VRAM used: 0.00 MB
```

Have you check the GPU usage during the inference ?  How much  memory total of the GPU?

I assume only CPU with no any other features open. The inference process would be so slow to response.

**Comment by lunamidori5** [comment]
@arbianqx if you would like GPU support you will need to add that to the models yaml file see here on how to do that - https://localai.io/howtos/easy-model-import-downloaded/

**Comment by arbianqx** [comment]
@lunamidori5 I have already completed those examples. I went by the docs step by step. It seems there's something missing

**Comment by lunamidori5** [comment]
@arbianqx models yaml file please <3

**Comment by arbianqx** [comment]
Yes sure. My plan is to use Mistral Models or such, but I started with the sample provided, by docs.

`backend: llama
context_size: 2000
name: lunademo
parameters:
  model: luna-ai-llama2-uncensored.Q4_K_M.gguf
  temperature: 0.2
  top_k: 40
  top_p: 0.65
roles:
  assistant: 'ASSISTANT:'
  system: 'SYSTEM:'
  user: 'USER:'
template:
  chat: lunademo-chat
  completion: lunademo-completion
f16: true
gpu_layers: 4
`

**Comment by lunamidori5** [comment]
@arbianqx so both your host and docker have cuda installed? Can you please post your openai v0 request?

**Comment by arbianqx** [comment]
@lunamidori5 Yupp cuda and docker. I was using the curl option provided by docs.

**Comment by lunamidori5** [comment]
@arbianqx this one? there is like... 5 in the how tos, so just making sure
```bash
curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "lunademo",
     "messages": [{"role": "user", "content": "How are you?"}],
     "temperature": 0.9 
   }'
   ```

**Comment by arbianqx** [comment]
@lunamidori5 I'm sorry if I'm not providing all the infos. Yes I was using this sample.

**Comment by lunamidori5** [comment]
@arbianqx Your good!! Alright one moment let me look everything over

**Comment by lunamidori5** [comment]
@arbianqx what is the error from the openai v0 request?

**Comment by arbianqx** [comment]
@lunamidori5 when I curl, it keeps hanging and response is being returned. Also when looking at logs it appears gprc error connection refused!

**Comment by lunamidori5** [comment]
``rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:39895: connect: connection refused"`` is not a error, it just means the model is not loaded yet and should show up under normal use.

@arbianqx  this being said, do you have a older intel CPU or more than one GPU (even if you are running on CPU it still better for me to ask)?

**Comment by arbianqx** [comment]
yes, no worries. AMD cpu (EPYC model), 8x A100 nvidia (40gb vram). I'm limiting the usage of gpu's by specifying how many I want to use. `--gpus '"device=1"'`

**Comment by lunamidori5** [comment]
So there is a fun bug with llama.cpp, those with more than one GPU (even when running on CPU) seem to make 7b models loop.

**Comment by lunamidori5** [comment]
@arbianqx try this openai v0 request to see if the model is looping
```bash
curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "lunademo",
     "messages": [{"role": "user", "content": "How are you?"}],
     "temperature": 0.9 ,
     "stream": true
   }'
   ```

**Comment by arbianqx** [comment]
@lunamidori5 interesting. Let me spin up a new container and try it out. What is your suggestion. To spin up with just one gpu?

**Comment by lunamidori5** [comment]
@arbianqx use a not 7b model, look for a 13b or bigger.

**Comment by arbianqx** [comment]
@lunamidori5 downloading a 13b as we speak. Should I leave a default model config, or specify one? The model I'm planning to test now, is this: `huggingface@TheBloke/Yarn-Llama-2-13B-128K-GGUF/yarn-llama-2-13b-128k.Q5_K_M.gguf`

**Comment by lunamidori5** [comment]
@arbianqx follow the [how to](https://localai.io/howtos/easy-model-import-downloaded/) on setting up a model, try not to run the model raw

**Comment by arbianqx** [comment]
@lunamidori5 template is different on what this model supports, but I made some changes on configs. It seems now, it's behaving somewhat the same.

```
2:52PM DBG Request received: 
2:52PM DBG Configuration read: &{PredictionOptions:{Model:yarn-llama-2-13b-128k.Q5_K_M.gguf Language: N:0 TopP:0.7 TopK:80 Temperature:0.9 Maxtokens:0 Echo:false Batch:0 F16:false IgnoreEOS:false RepeatPenalty:0 Keep:0 MirostatETA:0 MirostatTAU:0 Mirostat:0 FrequencyPenalty:0 TFZ:0 TypicalP:0 Seed:0 NegativePrompt: RopeFreqBase:0 RopeFreqScale:0 NegativePromptScale:0 UseFastTokenizer:false ClipSkip:0 Tokenizer:} Name:bloke13k F16:true Threads:4 Debug:true Roles:map[] Embeddings:false Backend:llama TemplateConfig:{Chat:chat ChatMessage: Completion:completion Edit: Functions:} PromptStrings:[] InputStrings:[] InputToken:[] functionCallString: functionCallNameString: FunctionsConfig:{DisableNoAction:false NoActionFunctionName: NoActionDescriptionName:} FeatureFlag:map[] LLMConfig:{SystemPrompt: TensorSplit: MainGPU: RMSNormEps:0 NGQA:0 PromptCachePath: PromptCacheAll:false PromptCacheRO:false MirostatETA:0 MirostatTAU:0 Mirostat:0 NGPULayers:4 MMap:false MMlock:false LowVRAM:false Grammar: StopWords:[] Cutstrings:[] TrimSpace:[] ContextSize:4096 NUMA:false LoraAdapter: LoraBase: NoMulMatQ:false DraftModel: NDraft:0 Quantization:} AutoGPTQ:{ModelBaseName: Device: Triton:false UseFastTokenizer:false} Diffusers:{PipelineType: SchedulerType: CUDA:false EnableParameters: CFGScale:0 IMG2IMG:false ClipSkip:0 ClipModel: ClipSubFolder:} Step:0 GRPC:{Attempts:0 AttemptsSleepTime:0} VallE:{AudioPath:}}
2:52PM DBG Parameters: &{PredictionOptions:{Model:yarn-llama-2-13b-128k.Q5_K_M.gguf Language: N:0 TopP:0.7 TopK:80 Temperature:0.9 Maxtokens:0 Echo:false Batch:0 F16:false IgnoreEOS:false RepeatPenalty:0 Keep:0 MirostatETA:0 MirostatTAU:0 Mirostat:0 FrequencyPenalty:0 TFZ:0 TypicalP:0 Seed:0 NegativePrompt: RopeFreqBase:0 RopeFreqScale:0 NegativePromptScale:0 UseFastTokenizer:false ClipSkip:0 Tokenizer:} Name:bloke13k F16:true Threads:4 Debug:true Roles:map[] Embeddings:false Backend:llama TemplateConfig:{Chat:chat ChatMessage: Completion:completion Edit: Functions:} PromptStrings:[] InputStrings:[] InputToken:[] functionCallString: functionCallNameString: FunctionsConfig:{DisableNoAction:false NoActionFunctionName: NoActionDescriptionName:} FeatureFlag:map[] LLMConfig:{SystemPrompt: TensorSplit: MainGPU: RMSNormEps:0 NGQA:0 PromptCachePath: PromptCacheAll:false PromptCacheRO:false MirostatETA:0 MirostatTAU:0 Mirostat:0 NGPULayers:4 MMap:false MMlock:false LowVRAM:false Grammar: StopWords:[] Cutstrings:[] TrimSpace:[] ContextSize:4096 NUMA:false LoraAdapter: LoraBase: NoMulMatQ:false DraftModel: NDraft:0 Quantization:} AutoGPTQ:{ModelBaseName: Device: Triton:false UseFastTokenizer:false} Diffusers:{PipelineType: SchedulerType: CUDA:false EnableParameters: CFGScale:0 IMG2IMG:false ClipSkip:0 ClipModel: ClipSubFolder:} Step:0 GRPC:{Attempts:0 AttemptsSleepTime:0} VallE:{AudioPath:}}
2:52PM DBG Prompt (before templating): How are you?
2:52PM DBG Stream request received
2:52PM DBG Template found, input modified to: Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
How are you?

### Response:
2:52PM DBG Prompt (after templating): Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
[172.17.0.1]:33642 200 - POST /v1/chat/completions
How are you?

### Response:
2:52PM DBG Sending chunk: {"created":1700232451,"object":"chat.completion.chunk","id":"4fa00984-b660-4c67-8d81-4f1fbaac2875","model":"bloke13k","choices":[{"index":0,"delta":{"role":"assistant","content":""}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}

2:52PM DBG Loading model llama from yarn-llama-2-13b-128k.Q5_K_M.gguf
2:52PM DBG Model already loaded in memory: yarn-llama-2-13b-128k.Q5_K_M.gguf
``` 

The curl is as follows:
```
curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "bloke13k",
     "messages": [{"role": "user", "content": "How are you?"}],
     "temperature": 0.9 ,
     "stream": true
   }'
```

This is the response:
```
data: {"created":1700232451,"object":"chat.completion.chunk","id":"4fa00984-b660-4c67-8d81-4f1fbaac2875","model":"bloke13k","choices":[{"index":0,"delta":{"role":"assistant","content":""}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
```

**Comment by lunamidori5** [comment]
@arbianqx try this yaml
(note please make sure that it starts with the backend and you have your settings between context and name)
```yaml
backend: llama
context_size: 4096
f16: true
cuda: true
gpu_layers: 4
threads: 2
low_vram: false
mmap: true
mmlock: false
name: bloke13k
feature_flags:
    usage: false
parameters:
  model: yarn-llama-2-13b-128k.Q5_K_M.gguf
  temperature: 0.2
  top_k: 80
  top_p: 0.7
template:
  chat: chat
  completion: completion
  ```

**Comment by lunamidori5** [comment]
Also deeply sorry for the slow reply!

**Comment by lunamidori5** [comment]
well its working! You can set stream to false to wait until its done! @arbianqx

**Comment by arbianqx** [comment]
@lunamidori5 trying this right now. As per right now, it keeps hanging there.
<img width="1326" alt="Screenshot 2023-11-17 at 4 11 41 PM" src="https://github.com/mudler/LocalAI/assets/79308777/e67f3a56-5fec-44d2-ab99-c255f3c5b287">

**Comment by arbianqx** [comment]
@lunamidori5 lowered the temp to 0.2 and removed top_k and top_p. Also I offloaded more layers to gpu by setting that to 40. However, i'm still not getting the response.

**Comment by MillionthOdin16** [comment]
I'm seeing the same errors on Docker with CPU only. Tried multiple different GGUF models.

`curl http://localhost:7801/v1/chat/completions -H "Content-Type: application/json" -d "{\"model\": \"mistral\", \"messages\": [{\"role\": \"user\", \"content\": \"How are you?\"}], \"temperature\": 0.1}"`

```{"error":{"code":500,"message":"rpc error: code = Unknown desc = unimplemented","type":""}}```
