### ISSUE TITLE
local build run failed for rwkv backend

### ISSUE THREAD

**Issue by redstarxz** [mudler/LocalAI#1307]
**LocalAI version:**
LocalAI version v1.40.0-38-g3e35b20 (3e35b20a0201db39ac7973c4e2b6b528f3d044b2)
**Environment, CPU architecture, OS, and Version:**
 mac m1
 Darwin Kernel Version 22.6.0: arm 64

**Describe the bug**

load rwkv model failed, chat api request return 500:

Request: 

 curl http://localhost:8989/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "outv4.bin",            
     "messages": [{"role": "user", "content": "How are you?"}],
     "temperature": 0.9, "top_p": 0.8, "top_k": 80
   }'

{"error":{"code":500,"message":"could not load model - all backends returned error: 17 errors occurred:\n\t* could not load model: rpc error: code = Canceled desc = \n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = failed loading model\n\t* could not load model: rpc error: code = Unknown desc = could not load model\n\t* could not load model: rpc error: code = Unknown desc = unable to load model\n\t* grpc process not found: /tmp/localai/backend_data/backend-assets/grpc/stablediffusion. some backends(stablediffusion, tts) require LocalAI compiled with GO_TAGS\n\t* grpc process not found: /tmp/localai/backend_data/backend-assets/grpc/piper. some backends(stablediffusion, tts) require LocalAI compiled with GO_TAGS\n\n","type":""}}%        

**To Reproduce**

**Expected behavior**
load rwkv model success,  api return sucess

**Logs**
LOG : 
3:00PM DBG [rwkv] Attempting to load
3:00PM DBG Loading model rwkv from outv4.bin
3:00PM DBG Loading model in memory from file: models/outv4.bin
3:00PM DBG Loading Model outv4.bin with gRPC (file: models/outv4.bin) (backend: rwkv): {backendString:rwkv model:outv4.bin threads:4 assetDir:/tmp/localai/backend_data context:{emptyCtx:{}} gRPCOptions:0x1400046e1e0 externalBackends:map[] grpcAttempts:20 grpcAttemptsDelay:2 singleActiveBackend:false parallelRequests:false}
3:00PM DBG Loading GRPC Process: /tmp/localai/backend_data/backend-assets/grpc/rwkv
3:00PM DBG GRPC Service for outv4.bin will be running at: '127.0.0.1:64113'
3:00PM DBG GRPC Service state dir: /var/folders/yj/wt9vbj1s34vb69qyywcgwxlh0000gn/T/go-processmanager2591975212
3:00PM DBG GRPC Service Started
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:64113: connect: connection refused"
3:00PM DBG GRPC(outv4.bin-127.0.0.1:64113): stderr 2023/11/20 15:00:07 gRPC Server listening at 127.0.0.1:64113
3:00PM DBG GRPC Service Ready
3:00PM DBG GRPC: Loading model with options: {state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:<nil>} sizeCache:0 unknownFields:[] Model:outv4.bin ContextSize:512 Seed:0 NBatch:512 F16Memory:false MLock:false MMap:false VocabOnly:false LowVRAM:false Embeddings:false NUMA:false NGPULayers:0 MainGPU: TensorSplit: Threads:4 LibrarySearchPath:/tmp/localai/backend_data/backend-assets/gpt4all RopeFreqBase:0 RopeFreqScale:0 RMSNormEps:0 NGQA:0 ModelFile:models/outv4.bin Device: UseTriton:false ModelBaseName: UseFastTokenizer:false PipelineType: SchedulerType: CUDA:false CFGScale:0 IMG2IMG:false CLIPModel: CLIPSubfolder: CLIPSkip:0 Tokenizer: LoraBase: LoraAdapter: LoraScale:0 NoMulMatQ:false DraftModel: AudioPath: Quantization: MMProj: RopeScaling: YarnExtFactor:0 YarnAttnFactor:0 YarnBetaFast:0 YarnBetaSlow:0}
3:00PM DBG [rwkv] Fails: could not load model: rpc error: code = Unknown desc = could not load model

**Additional context**

**Comment by Aisuko** [comment]
Hi @redstarxz  we have some examples of rwkv in https://github.com/go-skynet/model-gallery/blob/main/rwkv-raven-1b.yaml. Please check the example. I am not if `outv4.bin`'s format is correct.

**Comment by redstarxz** [comment]
> Hi @redstarxz we have some examples of rwkv in https://github.com/go-skynet/model-gallery/blob/main/rwkv-raven-1b.yaml. Please check the example. I am not if `outv4.bin`'s format is correct.
Thanks, Finaly, I found the reason,  for rwkv backend,  the token file name must fit with the model file name...
