### ISSUE TITLE
Docs request: Docker hub image

### ISSUE THREAD

**Issue by jamesbraza** [mudler/LocalAI#1314]
**Is your feature request related to a problem? Please describe.**

Trying to directly run LocalAI's Docker container without Docker compose fails, because obviously this is the wrong base image:

```bash
> docker run --rm -p 8080:8080 quay.io/go-skynet/local-ai:latest
Unable to find image 'quay.io/go-skynet/local-ai:latest' locally
latest: Pulling from go-skynet/local-ai
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```

**Describe the solution you'd like**

Can we document how to `docker run` the LocalAI container, without locally building it?

**Describe alternatives you've considered**

I don't want to have to clone the LocalAI repo and then run `docker compose up`.  I would rather just run `docker run` straight away.

**Additional context**

**Comment by lunamidori5** [comment]
running docker compose with the yaml file does what you want docker run to do @jamesbraza

**Comment by jamesbraza** [comment]
I am trying to avoid building the Docker container myself.  Running `docker compose up` will also perform a local build step.

I am wondering, is there a Docker hub image already in existence?  How can I avoid the build step on my Mac?

**Comment by mudler** [comment]
@jamesbraza did you check https://localai.io/basics/getting_started/#docker ? maybe that should go upper as probably it's an easy miss

**Comment by jamesbraza** [comment]
Thanks for sharing that, following the linked page's instructions:

```bash
> docker compose down
> docker system prune --all --force
> docker run -p 8080:8080 -v $PWD/models:/models -ti --rm quay.io/go-skynet/local-ai:latest --models-path /models
Unable to find image 'quay.io/go-skynet/local-ai:latest' locally
latest: Pulling from go-skynet/local-ai
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```

The moral of the story is, LocalAI's Docker can't be run without first locally building.

I am wondering, is there some way I can `docker pull` a pre-built image from Docker Hub? Something like [ollama/ollama on Docker Hub](https://hub.docker.com/r/ollama/ollama), except for LocalAI

**Comment by jamesbraza** [comment]
Ah, and I see https://github.com/mudler/LocalAI/issues/1249 requests pre-built containers with ARM support

I think we can make that Docker docs section more findable, perhaps promoting it to its own How To page. I will leave this open until then

**Comment by lunamidori5** [comment]
@jamesbraza you are super welcome to add a how to for that (or just have one made with a outline for me to edit) <3

**Comment by jamesbraza** [comment]
I see the docs have changed around since I last was here, like the new changes! I opened https://github.com/mudler/LocalAI/pull/1614 for this.
