### ISSUE TITLE
Getting started with `lunademo` not working

### ISSUE THREAD

**Issue by jamesbraza** [mudler/LocalAI#1316]
**LocalAI version:**

https://github.com/mudler/LocalAI/tree/v1.40.0

**Environment, CPU architecture, OS, and Version:**

I am on a MacBook Pro with macOS Ventura 13.5.2:

```
> uname -a
Darwin N7L493PWK4 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64
```

**Describe the bug**

**To Reproduce**

```
> git clone git@github.com:mudler/LocalAI.git
> cd LocalAI
> git checkout tags/v1.40.0
> docker compose up --detach
> curl http://localhost:8080/models/apply -H "Content-Type: application/json" -d '{
    "id": "model-gallery@lunademo"
}'
> sleep 600
> ls -l models
-rw-r--r--  1 user  staff  4081004256 Nov 21 17:49 luna-ai-llama2-uncensored.Q4_K_M.gguf
-rw-r--r--  1 user  staff          23 Nov 21 17:49 luna-chat-message.tmpl
-rw-r--r--  1 user  staff         208 Nov 21 17:49 lunademo.yaml
> cat models/luna-chat-message.tmpl
{{.Input}}

ASSISTANT:
> curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
    "model": "lunademo",
    "messages": [{"role": "user", "content": "How are you?"}],
    "temperature": 0.9
}'
```

On the back end (`docker logs`) it says:

```
api-1  | 10:51PM ERR error processing message {SystemPrompt: Role: RoleName:user Content:How are you? MessageIndex:0} using template "luna-chat-message": template: prompt:1:2: executing "prompt" at <.Input>: can't evaluate field Input in type model.ChatMessageTemplateData. Skipping!
```

**Expected behavior**

I expect https://localai.io/howtos/easy-request-curl/ to work.  However, it's giving a weird error:

```
can't evaluate field Input in type model.ChatMessageTemplateData.
```

**Logs**

See above

**Additional context**

https://github.com/mudler/LocalAI/issues/1044 seems related

**Comment by jamesbraza** [comment]
Cc @lunamidori5

**Comment by jamesbraza** [comment]
This issue is unrelated to the model gallery I believe, it works in downloading the config files and model GGUF (`luna-ai-llama2-uncensored.Q4_K_M.gguf`).  Here are my files:

`luna-chat-message.tmpl`:

```none
{{.Input}}

ASSISTANT:
```

`lunademo.yaml`:

```yaml
backend: llama
context_size: 4096
f16: true
gpu_layers: 35
name: lunademo
parameters:
  model: luna-ai-llama2-uncensored.Q4_K_M.gguf
  temperature: 0.2
template:
  chat_message: luna-chat-message
threads: 10
```

I think it's something else. Any ideas? And thanks for your help

**Comment by lunamidori5** [comment]
@mudler this is the 4th report this week that something is not working, is the gallery getting updates?

**Comment by mudler** [comment]
> @mudler this is the 4th report this week that something is not working, is the gallery getting updates?

gallery is not on my radar at the moment, but functionality wise should be just fine as it is tested by the CI automatically too. Maybe a misconfiguration issue? Gonna otherwise try to have a look at it as soon as possible

**Comment by lunamidori5** [comment]
@mudler the yaml is failing due to GPU layers being listed on a CPU only image, is there a way to make the yaml not do that?

**Comment by jamesbraza** [comment]
@lunamidori5 thanks for looking into this. I am not sure that's the fix though, setting `gpu_layers: 0` I still get this error within the Docker container:

```none
api-1  | 5:25PM ERR error processing message {SystemPrompt: Role: RoleName:user Content:How are you? MessageIndex:0} using template "luna-chat-message": template: prompt:1:2: executing "prompt" at <.Input>: can't evaluate field Input in type model.ChatMessageTemplateData. Skipping!
```

With the relevant portion being:

> can't evaluate field Input in type model.ChatMessageTemplateData. Skipping!

Why is the `.Input` not being respected in the template?

**Comment by lunamidori5** [comment]
@jamesbraza remove f16 and gpu layers fully 
Thats not the format localai uses for the template? see the [how to](https://localai.io/howtos/easy-model-import-downloaded/) for more info

**Comment by jamesbraza** [comment]
> Thats not the format localai uses for the template? see the [how to](https://localai.io/howtos/easy-model-import-downloaded/) for more info

For what it's worth, what I am using matches that.

<img height="130" alt="image" src="https://github.com/mudler/LocalAI/assets/8990777/d79d08d3-bfaa-4640-8d27-e41d9cebb2e2">

Also, in this issue's original post, the commands I ran use the model gallery's source directly ([link](https://github.com/go-skynet/model-gallery/blob/40df46515d9059dd772f27c203993f415d135b27/lunademo.yaml#L23-L28)), so if the template format is incorrect, we should update the model gallery's template.

---

Also, setting `f16` to `false` unfortunately it's still not working. Using `DEBUG=true`, I can see the model is loaded using the `llama_model_loader`, but then the prompt is never passed to it, and it just hangs.  I believe there may be some bug where, with a template error, the prompt never makes it to the model

**Comment by jamesbraza** [comment]
Ah figured it out.  `lunademo.yaml` should be:

```diff
template:
-  chat_message: luna-chat-message
+  chat: luna-chat-message
```

I will open a PR to fix this shortly

**Comment by jamesbraza** [comment]
Thanks for also pointing out on `f16` vs `gpu_layers` btw!  I was able to get it working now 👍 

I am wondering if you should make two "getting started" versions, one for CPU and one for GPU @lunamidori5

**Comment by lunamidori5** [comment]
@jamesbraza there is no getting started for a lunademo, but yes Ill add a thing about a GPU copy soon on the how to set up a model page
