### ISSUE TITLE
feat: during download, leave model name as `.gguf.partial`

### ISSUE THREAD

**Issue by jamesbraza** [mudler/LocalAI#1329]
**Is your feature request related to a problem? Please describe.**

It can take a few minutes to download a model. Unless you have the model status URL to `curl` via `curl -s http://localhost:8080/models/jobs/123abc`, it's hard to know if the download has completed.

**Describe the solution you'd like**

I propose the LocalAI server's downloader place the file at `model-name.gguf.partial`, and then when the download has completed, it's renamed to `model-name.gguf`.

This `.partial` extension would make it clear when the download has actually completed.

**Describe alternatives you've considered**

None right now

**Additional context**

N/a

**Comment by mudler** [comment]
good point - definetly we can also support resuming download with it
