### ISSUE TITLE
Crashes attempting to run Luna-AI model

### ISSUE THREAD

**Issue by ThommoMC** [mudler/LocalAI#1331]
**LocalAI version:**

v1.40.0

**Environment, CPU architecture, OS, and Version:**

Compiled for CUDA on Linux thommopc 6.6.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 20 Nov 2023 23:18:21 +0000 x86_64 GNU/Linux

**Describe the bug**

Attempting to load the Luna AI model using the YAML config from this guide https://localai.io/howtos/easy-model-import-downloaded/ will cause LocalAI to crash
**To Reproduce**

Follow the instructions for that guide and attempt to prompt the model
**Expected behavior**

The model responds with a answer  
**Logs**

See attached text file
[localaierror.txt](https://github.com/mudler/LocalAI/files/13462776/localaierror.txt)

**Additional context**

Running the model without a config allows it to work

**Comment by lunamidori5** [comment]
Notes from Discord 
Removing the Backend from the yaml file, lets the model load...
