### ISSUE TITLE
Vall-E-X backend still broken

### ISSUE THREAD

**Issue by TwinFinz** [mudler/LocalAI#1394]
**LocalAI version:**
v2.0.0-cublas-cuda12-ffmpeg

**Environment, CPU architecture, OS, and Version:**
Linux LocalAi-GPT 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux

**Describe the bug**
Fails to find something (expect it is tokenizer its failing to find)

**To Reproduce**
curl http://localhost:8080/tts -H "Content-Type: application/json" -H "Authorization: Bearer sk-xxx" -d '{ "backend": "bark", "input":"Hello!" }'

**Expected behavior**
Output Audio

**Logs**
1:31AM DBG GRPC(-127.0.0.1:34935): stderr Traceback (most recent call last):
1:31AM DBG GRPC(-127.0.0.1:34935): stderr   File "/build/backend/python/vall-e-x/ttsvalle.py", line 14, in <module>
1:31AM DBG GRPC(-127.0.0.1:34935): stderr     from utils.generation import SAMPLE_RATE, generate_audio, preload_models
1:31AM DBG GRPC(-127.0.0.1:34935): stderr   File "/build/backend/python/vall-e-x/utils/generation.py", line 47, in <module>
1:31AM DBG GRPC(-127.0.0.1:34935): stderr     text_tokenizer = PhonemeBpeTokenizer(tokenizer_path="./utils/g2p/bpe_69.json")
1:31AM DBG GRPC(-127.0.0.1:34935): stderr   File "/build/backend/python/vall-e-x/utils/g2p/__init__.py", line 13, in __init__
1:31AM DBG GRPC(-127.0.0.1:34935): stderr     self.tokenizer = Tokenizer.from_file(tokenizer_path)
1:31AM DBG GRPC(-127.0.0.1:34935): stderr Exception: No such file or directory (os error 2)

**Additional context**
this is a fresh pull of the LocalAi v2 image docker was freshly reinstalled/reset with all previous images removed prior.

**Comment by mudler** [comment]
Vall-e-x is currently fixed in master. Closing the issue

**Comment by bdqfork** [comment]
I got same problem today, used docker image `quay.io/go-skynet/local-ai:v2.3.0-cublas-cuda12-ffmpeg`

**Comment by mudler** [comment]
I've tested it in the container today and could confirm - the fix was easy, the problem was that unfortunately tests don't cover that e2e. It should be fixed in master now!
