### ISSUE TITLE
Unable to load StableDiffuser SDXL Model

### ISSUE THREAD

**Issue by JamesNyeVRGuy** [mudler/LocalAI#1426]
**LocalAI version:**
[9aa2a7c](https://github.com/mudler/LocalAI/commit/9aa2a7ca13c5fa47ea46eb5359eec5d2c9d7f5ad)

**Environment, CPU architecture, OS, and Version:**
Proxmox Ubuntu 20.04, Docker Compose

**Describe the bug**
Tried to load <stabilityai/sdxl-turbo> on the stable diffusion .yaml file, 

```name: sdxl-turbo
parameters:
  model: stabilityai/sdxl-turbo
backend: diffusers

# Force CPU usage - set to true for GPU
f16: false
diffusers:
  pipeline_type: StableDiffusionXLPipeline
  cuda: false # Enable for GPU usage (CUDA)
  scheduler_type: dpm_2_a
```
  
  And was unable to generate an image! Got several errors, end of file and RPC issues. 

**To Reproduce**
Follow the https://localai.io/howtos/easy-setup-sd/ and replace with sdxl-turbo!

**Expected behavior**
Generate an image of two boxes, one blue and one red.

**Comment by lunamidori5** [comment]
Cross posting with #1408 - Error is posted there
