### ISSUE TITLE
CPPLLAMA_VERSION?=XXX in Makefile is not used for llama.cpp build

### ISSUE THREAD

**Issue by wuxxin** [mudler/LocalAI#1436]
**LocalAI version:** Master (https://github.com/mudler/LocalAI/commit/7641f92cdedd8f551f9e999402a726ae4e02dca9)

**Describe the bug**
current commit for llama.cpp in Makefile is:
```
CPPLLAMA_VERSION?=8a7b2fa528f130631a5f43648481596ab320ed5a
```
but backend/cpp/llama/Makefile uses a default of 
```
LLAMA_VERSION?=d9b33fe95bd257b36c84ee5769cc048230067d6f
```
which is from around november 2023

CPPLLAMA_VERSION is not forwarded to LLAMA_VERSION and because of this: commit d9b33* of llama.cpp is build instead of 8a7b* (or whatever is defined in CPPLLAMA_VERSION)

**To Reproduce**
make CPPLLAMA_VERSION=948ff137ec37f1ec74c02905917fa0afc9b97514 build

**Expected behavior**
localai builds llama.cpp out of commit 948ff*

**Actual result**
localai builds llamap.cpp out of commit d9b33*

**Additional Resources**
i made a archlinux package for localai,
https://aur.archlinux.org/packages?K=localai-git
with CPU, CUDA and ROCM version. 
See https://github.com/wuxxin/aur-packages/blob/main/localai-git/PKGBUILD
for the patches including this issue

**Comment by mudler** [comment]
good catch @wuxxin ! do you feel to take a stab at it? I'm currently busy in #1435 trying to make diffusers on par, this issue would be my next one otherwise
