### ISSUE TITLE
"SIGILL: illegal instruction" causing "error reading from server: EOF"

### ISSUE THREAD

**Issue by that1guy** [mudler/LocalAI#1453]
My CPU only supports AVX,but not AVX2 or AVX512.  This is causing issues I can't seem to workaround even when rebuidling with proper CPU Flags.  See my .env

```
## Set number of threads.
## Note: prefer the number of physical cores. Overbooking the CPU degrades performance notably.
THREADS=2

## Specify a different bind address (defaults to ":8080")
# ADDRESS=127.0.0.1:8080

## Define galleries.
## models will to install will be visible in `/models/available`
GALLERIES=[{"name":"model-gallery", "url":"github:go-skynet/model-gallery/index.yaml"}, {"url": "github:go-skynet/model-gallery/huggingface.yaml","name":"huggingface"}]

## Default path for models
MODELS_PATH=/models

## Enable debug mode
DEBUG=true

## Disables COMPEL (Lets Stable Diffuser work, uncomment if you plan on using it)
# COMPEL=0

## Enable/Disable single backend (useful if only one GPU is available)
# SINGLE_ACTIVE_BACKEND=true

## Specify a build type. Available: cublas, openblas, clblas.
BUILD_TYPE=openblas

## Uncomment and set to true to enable rebuilding from source
REBUILD=true

## Removing CPU FLAGS
CMAKE_ARGS="-DLLAMA_F16C=OFF -DLLAMA_AVX512=OFF -DLLAMA_AVX2=OFF -DLLAMA_AVX=OFF -DLLAMA_FMA=OFF -DLLAMA_F16C=OFF"

## Enable go tags, available: stablediffusion, tts
## stablediffusion: image generation with stablediffusion
## tts: enables text-to-speech with go-piper 
## (requires REBUILD=true)
#
#GO_TAGS=tts

## Path where to store generated images
# IMAGE_PATH=/tmp

## Specify a default upload limit in MB (whisper)
# UPLOAD_LIMIT

# HUGGINGFACEHUB_API_TOKEN=Token here
```

**LocalAI version:**
Latest

**Environment, CPU architecture, OS, and Version:**

- Supermicro 2U X9DRI-LN4F Board
- 2x Intel Xeon E5-2670 2.6ghz 16-Cores
- 64gb mem
- Latest Unraid OS 6.12.6
- Using Docker Compose

**Describe the bug**

**To Reproduce**
Issue HTTP Request:
```
curl http://localhost:9000/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "lunademo",
     "messages": [{"role": "user", "content": "How are you?"}],
     "temperature": 0.9 
   }'
```

Receive HTTP 500 Error Response:
```
{"error":{"code":500,"message":"could not load model: rpc error: code = Unavailable desc = error reading from server: EOF","type":""}}
```

**Expected behavior**
HTTP 200 response

**Logs**

```
See Attached File
[Boot & Error Logs.txt](https://github.com/mudler/LocalAI/files/13695032/Boot.Error.Logs.txt)

```

**Additional context**
Using following model and configs:
<img width="737" alt="image" src="https://github.com/mudler/LocalAI/assets/1218940/96ffe210-c47a-440c-9c3a-ee82b65dc007">

Lunademo.yaml:
```
backend: llama
context_size: 4096
name: lunademo
parameters:
  model: luna-ai-llama2-uncensored.Q4_K_M.gguf
  temperature: 0.2
template:
  chat: luna-chat-message
threads: 10

```

**Comment by justaCasualCoder** [comment]
Same here... Compiling from source with latest commit seeing if it is fixed...

**Comment by that1guy** [comment]
Glad to hear I'm not alone.  Let me know if you have a breakthrough. :)

**Comment by justaCasualCoder** [comment]
Great News! Got it working! Building from source with this modified `Dockerfile` worked! Here are the steps I used:

- Clone the Repo
```
git clone https://github.com/mudler/LocalAI.git
cd LocalAI
```
- Download the attached `Dockerfile`
```
wget https://github.com/mudler/LocalAI/files/13705244/Dockerfile.txt -O Dockerfile
```
- Build
```
docker build -t localai .
```
[Dockerfile](https://github.com/mudler/LocalAI/files/13705244/Dockerfile.txt)

**Comment by that1guy** [comment]
@justaCasualCoder thanks for digging in and sharing your findings!  When I manually ran a diff between the Dockerfile you found and the one in the main repo I noticed all your Dockerfile was doing was adding the same CPU flags.  

Ultimately, I just pulled down the new 2.0.1 Dockerfile and everything worked.   I guess I was just experience an edge case scenario related to 2.0.0.
