### ISSUE TITLE
Cannot pull Docker image from quay.io

### ISSUE THREAD

**Issue by langchain4j** [mudler/LocalAI#1541]
**LocalAI version:**
latest

**Environment, CPU architecture, OS, and Version:**
13th Gen Intel(R) Core(TM) i5-13400   2.50 GHz
64-bit operating system, x64-based processor
Windows 11 Pro 22621.2861

**Describe the bug**
`docker pull quay.io/go-skynet/local-ai:latest` does not finish, just hangs indefinitely

**To Reproduce**
`docker pull quay.io/go-skynet/local-ai:latest`

**Expected behavior**
Should pull image without problems

**Logs**
```
PS C:\dev> docker pull quay.io/go-skynet/local-ai:latest
latest: Pulling from go-skynet/local-ai
18f2c3b7ca52: Waiting                                                                                                                                               
8988ac7a69cc: Waiting                                                                                                                                               
d8d278fc41a9: Waiting                                                                                                                                               
32e75cdbd7a0: Waiting                                                                                                                                               
4445172115f2: Waiting                                                                                                                                               
e3ca2e15a286: Waiting                                                                                                                                               
251543e13596: Waiting
9979f8a64fa0: Waiting
a69bf6f0832a: Waiting
f890b3a79898: Waiting
2ea72ad1e176: Waiting
1df74f924389: Waiting
3d28119feef1: Waiting
ec7895c8ca33: Waiting
4ebe7e10b6a5: Waiting
a5633011e498: Waiting
ccdef4b734bc: Waiting
```

**Additional context**
This is not the first time I am getting this problem.
Would be great if you could host images on docker hub, I did not have such problems with it so far.

Thank you for the awesome project!

**Comment by mudler** [comment]
I've used quay.io initially as I've created the org and applied with dockerhub for a free tier for the OSS program, let's see if it will get accepted. I'm afraid we would hit otherwise pull requests limits.

**Comment by langchain4j** [comment]
BTW DockerHub Pro plan (5 bucks/month) has 5k pulls/day

**Comment by mudler** [comment]
let's keep this open until this is properly documented and pushed by our CI

**Comment by mudler** [comment]
the images repository is here : https://hub.docker.com/repository/docker/localai/localai/tags?page=1&ordering=last_updated

**Comment by JoshuaCWebDeveloper** [comment]
I spent the whole day trying to download the quay.io image with no success, the DockerHub image pulled first try! FYI, the public DockerHub link is: https://hub.docker.com/r/localai/localai/tags?page=1&ordering=last_updated

**Comment by mudler** [comment]
closing now this ticket as docs were updated too, and images are available already
