### ISSUE TITLE
vvlm not found as backend after localai is built locally

### ISSUE THREAD

**Issue by vshapenko** [mudler/LocalAI#1561]
**LocalAI version:**
Master branch

**Environment, CPU architecture, OS, and Version:**
Linux DGXA-Node27 5.15.0-1042-nvidia #42-Ubuntu SMP Wed Nov 15 20:28:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
I build localai locally, configured vllm model like this: 

`name: vllm
backend: vllm
parameters:
    model: "qwen/Qwen-7B-Chat"`

After run and request to completion api i get the error that vllm backend is not found. What are additional steps to configure vllm backend locally?

**Comment by vshapenko** [comment]
I am getting this error: 12:21PM DBG Loading model in memory from file: /home/vshapenko/LocalAI/models/qwen/Qwen-7B-Chat
12:21PM DBG Loading Model qwen/Qwen-7B-Chat with gRPC (file: /home/vshapenko/LocalAI/models/qwen/Qwen-7B-Chat) (backend: vllm): {backendString:vllm model:qwen/Qwen-7B-Chat threads:4 assetDir:/tmp/localai/backend_data context:{emptyCtx:{}} gRPCOptions:0xc0007f8780 externalBackends:map[] grpcAttempts:20 grpcAttemptsDelay:2 singleActiveBackend:false parallelRequests:false}

local ai is build with build_type=cublas. No

**Comment by mudler** [comment]
are you building the container image? as vLLM is a python backend it is not compiled and part of the local-ai binary, you actually need to either specify the binary of the vllm service or it's address if already started.

For example:

```
./local-ai --external-grpc-backends "vllm:/path/to/the/vllm/backend"
```

If you cloned the repository and built local-ai manually, then would likely be:

```
./local-ai --external-grpc-backends "vllm:$PWD/backend/python/vllm/run.sh"
```

Note that you need to first create the conda environment with:

```
make -C backend/python/vllm
```

**Comment by vshapenko** [comment]
Thank you for detailed answer, awesome!

**Comment by mudler** [comment]
updating our docs in #1572

**Comment by abdulazizalatee** [comment]
Hello @vshapenko and @mudler,

I spent three days trying to run vllm. I read and reviewed all the documents, but I was unable to run it. I used Docker and from the source, but to no avail. Can you help me?
