### ISSUE TITLE
latest-cublas-cuda12 tag does not exist on DockerHub or Quay

### ISSUE THREAD

**Issue by roblandry** [mudler/LocalAI#1724]
**LocalAI version:**

<ins>Latest tags:</ins>  quay.io/go-skynet/local-ai:latest-cublas-cuda12 or localai/localai:latest-cublas-cuda12
<ins>Version tag:</ins>  quay.io/go-skynet/local-ai:v2.8.2-cublas-cuda12

**Environment, CPU architecture, OS, and Version:**

```sh
Linux ZEUS 6.1.64-Unraid #1 SMP PREEMPT_DYNAMIC Wed Nov 29 12:48:16 PST 2023 x86_64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz GenuineIntel GNU/Linux
```

**Describe the bug**

<ins>"latest" tag does not exist.</ins>
I've been using Version tags.
Reading the latest docs [container-images](https://localai.io/basics/getting_started/#container-images), it indicates a "latest" tag should exist.
You can validate it does not:  [DockerHub](https://hub.docker.com/r/localai/localai/tags?page=1&name=latest-cublas-cuda12)

**To Reproduce**

Update docker compose with latest tag 
```yaml
    image: quay.io/go-skynet/local-ai:latest-cublas-cuda12
```

Pull latest tag
```sh
❯ docker compose pull
```

**Expected behavior**

Tag exists and pulls

**Logs**

```sh
❯ docker compose pull
[+] Pulling 2/2
 ✘ api Error 
Error response from daemon: manifest for quay.io/go-skynet/local-ai:latest-cublas-cuda12 not found: manifest unknown: manifest unknown
```

**Additional context**

**Comment by olariuromeo** [comment]
I think the last one is master-cublas-cuda12

**Comment by Osigmae** [comment]
had the same issue, used localai/localai:master-cublas-cuda12 instead as it was there.

**Comment by roblandry** [comment]
Master is not the same as latest. Master would be more of a beta.

**Comment by phil-lipp** [comment]
It was working for v2.11, but now with the release of v2.12.X the "manifest unknown" pops up again for me

**Comment by Taikono-Himazin** [comment]
I think the problem is probably that the wrong tag name is listed in the documentation.
Probably "latest-gpu-nvidia-cuda-12" is correct.

[latest-gpu-nvidia-cuda-12](https://hub.docker.com/layers/localai/localai/latest-gpu-nvidia-cuda-12/images/sha256-f5b4f49748fc8f0c67652537a6b03ba71e752a367e44c24e731050bb8861c30a?context=explore)
