### ISSUE TITLE
Whisper V3 model can support long Audio input, can you add an API to support large Audio file as a whole?

### ISSUE THREAD

**Issue by ER-EPR** [mudler/LocalAI#1733]
**Is your feature request related to a problem? Please describe.**

Current whisper api can only take around 20MB audio file per request. Now whisper V3 can work with large audio file. Can you support it too. Eliminate the limitation on audio file size for whisper V3.
**Describe the solution you'd like**

Allow upload a large audio file.
call whisper with V3 model, transcribe.
Stream the text back to the user.
**Describe alternatives you've considered**

**Additional context**

**Comment by mudler** [comment]
good point, we need to update whisper

**Comment by ER-EPR** [comment]
> good point, we need to update whisper

but I still can't send 17MByte MP3 audio file to the API :
'''
ClientException
Client error: `POST http://192.168.110.70:8080/v1/audio/transcriptions` resulted in a `413 Request Entity Too Large` response: {"error":{"code":413,"message":"Request Entity Too Large","type":""}}
API request error : Client error: `POST http://192.168.110.70:8080/v1/audio/transcriptions` resulted in a `413 Request Entity Too Large` response: {"error":{"code":413,"message":"Request Entity Too Large","type":""}}
'''

**Comment by sfxworks** [comment]
```bash
curl http://172.16.1.193/v1/audio/transcriptions -H "Content-Type: multipart/form-data" -F file="@/tmp/audio.mp3" -F model="whisper-3"
{"error":{"code":413,"message":"Request Entity Too Large","type":""}}%
```

Yeah even a direct curl on a v3 model. I'm using the all in one cuda 12 image here.

**Comment by sfxworks** [comment]
```
Downsampled audio file and saved to /tmp/audio_downsampled.mp3 with bitrate 32k
Audio file size in MB: 16.477432
```
Even under that size, 
```
openai.APIStatusError: Error code: 413 - {'error': {'code': 413, 'message': 'Request Entity Too Large', 'type': ''}}
```

**Comment by sfxworks** [comment]
Hey so its currently undocumented but found it in discord

`UPLOAD_LIMIT` needs to be set to something higher. Set it to 50 and it works.

**Comment by ER-EPR** [comment]
set environment LOCALAI_UPLOAD_LIMIT right? Can I set it to 512?

**Comment by sfxworks** [comment]
donno but I've managed to upload at least to 100 give it a shot

**Comment by fullstackwebdev** [comment]
just for future reference, yes it works

`docker run -p 8080:8080 --gpus all --name local-ai2 -ti -e LOCALAI_UPLOAD_LIMIT=512 localai/localai:latest-aio-gpu-nvidia-cuda-12`
