### ISSUE TITLE
vLLM streaming mode only streams data once the inference is completely over

### ISSUE THREAD

**Issue by golgeek** [mudler/LocalAI#1748]
**LocalAI version:**
v2.8.2

**Describe the bug**
Current implementation uses vLLM's [LLMEngine](https://github.com/vllm-project/vllm/blob/main/vllm/engine/llm_engine.py#L40), which was designed for "offline batch inference".

This results in all batch of data being streamed by the Python backend only at the end of the inference of each part being streamed as soon as it's available.

**Expected behavior**
Stream each batch as soon as it's available by using asyncio and vLLM's AsyncLLMEngine instead of LLMEngine.

**Additional context**
PR incoming.

**Comment by mudler** [comment]
Thanks for the PR @golgeek , really appreciated! treating this as an enhancement as it was calling for an implementation. 

Do you have a twitter handle? I'd be happy to give a shout-out on twitter about this too :)

**Comment by golgeek** [comment]
Thanks for your prompt review!

My Twitter handle is the same as Github :)
