### ISSUE TITLE
backend: speechd

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#1766]
`speechd` seems a good addition to the TTS engines currently supported by LocalAI. However, it looks like the Licensing of speechd might be a blocker as it is GPL.

This is also being discussed here: https://github.com/brailcom/speechd/issues/874

**Comment by sthibaul** [comment]
The licensing would not be a blocker since the C api is LGPL, not GPL.

**Comment by mudler** [comment]
> The licensing would not be a blocker since the C api is LGPL, not GPL.

is the C api consuming behind the scenes code licensed under GPL? or the core is written in C and exposes api from the language?

**Comment by sthibaul** [comment]
speechd uses a client-server scheme. The server is GPL, the client library is LGPL. So applications can just use the LGPL library and not be affected by GPL propagation.
