### ISSUE TITLE
add openvino support for igpu acceleation

### ISSUE THREAD

**Issue by jsapede** [mudler/LocalAI#1768]
**Is your feature request related to a problem? Please describe.**
only SYCL acceleraiton is available but intel CPU, even old (> gen6) includes openvino acceleration witch works pretty well (equivalent to google coral for what i've tested on frigate)

enabling openvino could strongly accelerate models even in old / small / cheap systems, no need for cuda

**Describe the solution you'd like**
docker images including openvino and /dev/dri/renderD128 passthrough to access igpu

**Describe alternatives you've considered**

**Additional context**
buildind accelerated local hosted voice assistants for homeassistant including distil-whisper or whisper.cpp / wyioming protocol

**Comment by mudler** [comment]
Thanks for showing interest in LocalAI and OpenVINO , I'll close this one as there is already another one already opened here: https://github.com/mudler/LocalAI/issues/1722

**Comment by jsapede** [comment]
ok thanks !
