### ISSUE TITLE
feat: Add Bitsandbytes quantization for transformer backend

### ISSUE THREAD

**Issue by fakezeta** [mudler/LocalAI#1775]
**Is your feature request related to a problem? Please describe.**

Quantization is not available for transformer backend
**Describe the solution you'd like**

Add bitsandbytes 4bit quantization to be triggered by the user with the `low_vram` flag in the model definition
Additionally I propose to use the `f16` flag to change the `compute_dtype` to `bfloat16` for better optimization on Nvidia cards
**Describe alternatives you've considered**

**Additional context**

I've implemented this while fixing [#1774](https://github.com/mudler/LocalAI/issues/1774)
Issue opened for tracking

**Comment by mudler** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Quantization is not available for transformer backend **Describe the solution you'd like**
> 
> Add bitsandbytes 4bit quantization to be triggered by the user with the `low_vram` flag in the model definition Additionally I propose to use the `f16` flag to change the `compute_dtype` to `bfloat16` for better optimization on Nvidia cards **Describe alternatives you've considered**
> 
> **Additional context**
> 
> I've implemented this while fixing [#1774](https://github.com/mudler/LocalAI/issues/1774) Issue opened for tracking

good point @fakezeta! do you have already a PR? maybe we can take it from there

**Comment by fakezeta** [comment]
You know I'm old, give me some time 😄 
I think I'll do it tonight (CET).
