### ISSUE TITLE
Out of date huggingface-embeddings backend

### ISSUE THREAD

**Issue by TwinFinz** [mudler/LocalAI#1783]
**LocalAI version:**
LocalAI version: c8be839 (c8be839481222cf2ebedb316b804c705d6b012e9)

**Environment, CPU architecture, OS, and Version:**
Linux LocalAi 6.5.11-8-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-8 (2024-01-30T12:27Z) x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
Out of date huggingface-embeddings backend cause model to not load/function.

**To Reproduce**
Use the following yaml to attempt to use "nomic-embed" model.

## yaml ##
```
name: nomic-embed
backend: huggingface-embeddings
embeddings: true
parameters:
  model: nomic-ai/nomic-embed-text-v1
```

**Expected behavior**
Generate and return of embeddings.

**Logs**
7:52AM DBG Loading Model nomic-ai/nomic-embed-text-v1 with gRPC (file: /build/models/nomic-ai/nomic-embed-text-v1) (backend: huggingface-embeddings): {backendString:huggingface-embeddings model:nomic-ai/nomic-embed-text-v1 threads:4 assetDir:/tmp/localai/backend_data context:{emptyCtx:{}} gRPCOptions:0xc000338000 externalBackends:map[autogptq:/build/backend/python/autogptq/run.sh bark:/build/backend/python/bark/run.sh coqui:/build/backend/python/coqui/run.sh diffusers:/build/backend/python/diffusers/run.sh exllama:/build/backend/python/exllama/run.sh exllama2:/build/backend/python/exllama2/run.sh huggingface-embeddings:/build/backend/python/sentencetransformers/run.sh mamba:/build/backend/python/mamba/run.sh petals:/build/backend/python/petals/run.sh sentencetransformers:/build/backend/python/sentencetransformers/run.sh transformers:/build/backend/python/transformers/run.sh transformers-musicgen:/build/backend/python/transformers-musicgen/run.sh vall-e-x:/build/backend/python/vall-e-x/run.sh vllm:/build/backend/python/vllm/run.sh] grpcAttempts:20 grpcAttemptsDelay:2 singleActiveBackend:true parallelRequests:true}
7:52AM DBG Loading external backend: /build/backend/python/sentencetransformers/run.sh
7:52AM DBG Loading GRPC Process: /build/backend/python/sentencetransformers/run.sh
7:52AM DBG GRPC Service for nomic-ai/nomic-embed-text-v1 will be running at: '127.0.0.1:44505'
7:52AM DBG GRPC Service state dir: /tmp/go-processmanager1812659671
7:52AM DBG GRPC Service Started
7:52AM DBG GRPC(nomic-ai/nomic-embed-text-v1-127.0.0.1:44505): stderr Server started. Listening on: 127.0.0.1:44505
7:52AM DBG GRPC Service Ready
7:52AM DBG GRPC: Loading model with options: {state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:<nil>} sizeCache:0 unknownFields:[] Model:nomic-ai/nomic-embed-text-v1 ContextSize:0 Seed:0 NBatch:512 F16Memory:false MLock:false MMap:false VocabOnly:false LowVRAM:false Embeddings:true NUMA:false NGPULayers:0 MainGPU: TensorSplit: Threads:4 LibrarySearchPath: RopeFreqBase:0 RopeFreqScale:0 RMSNormEps:0 NGQA:0 ModelFile:/build/models/nomic-ai/nomic-embed-text-v1 Device: UseTriton:false ModelBaseName: UseFastTokenizer:false PipelineType: SchedulerType: CUDA:false CFGScale:0 IMG2IMG:false CLIPModel: CLIPSubfolder: CLIPSkip:0 ControlNet: Tokenizer: LoraBase: LoraAdapter: LoraScale:0 NoMulMatQ:false DraftModel: AudioPath: Quantization: MMProj: RopeScaling: YarnExtFactor:0 YarnAttnFactor:0 YarnBetaFast:0 YarnBetaSlow:0 Type:}
7:52AM DBG [WatchDog] Watchdog checks for idle connections
7:52AM DBG GRPC(nomic-ai/nomic-embed-text-v1-127.0.0.1:44505): stderr You try to use a model that was created with version 2.4.0.dev0, however, your version is 2.2.2. This might cause unexpected behavior or errors. In that case, try to update to the latest version.
7:52AM DBG GRPC(nomic-ai/nomic-embed-text-v1-127.0.0.1:44505): stderr
7:52AM DBG GRPC(nomic-ai/nomic-embed-text-v1-127.0.0.1:44505): stderr
7:52AM DBG GRPC(nomic-ai/nomic-embed-text-v1-127.0.0.1:44505): stderr
[192.168.0.106]:7512 500 - POST /embeddings

**Additional context**
Looks like something just needs to be updated. Should be pretty simple.

**Comment by mudler** [comment]
would need to be updated here: 

- https://github.com/mudler/LocalAI/blob/316de82f5189ec8ad1ba8b36f7bef99ab00c0700/backend/python/common-env/transformers/transformers.yml#L39 
- https://github.com/mudler/LocalAI/blob/316de82f5189ec8ad1ba8b36f7bef99ab00c0700/backend/python/common-env/transformers/transformers-rocm.yml#L41
- https://github.com/mudler/LocalAI/blob/316de82f5189ec8ad1ba8b36f7bef99ab00c0700/backend/python/common-env/transformers/transformers-nvidia.yml#L39

**Comment by TwinFinz** [comment]
Once I get back home I will do what I can to make a pull for this
specific issue

**Comment by TwinFinz** [comment]
Thank you! 😊

**Comment by TwinFinz** [comment]
AFAIK it should be fixed I have not tested it. But I updated the backend
version to a supported version as mentioned in model output and inkmoth(I
think) added the "trust remote code" so theoretically it should be
functional. If any issues are still there another issue can be opened. I
say go ahead and close it.

**Comment by mudler** [comment]
sounds good, thanks @TwinFinz ! it is also passing tests, so we should be safe too!
