### ISSUE TITLE
continue

### ISSUE THREAD

**Issue by olariuromeo** [mudler/LocalAI#1800]
**LocalAI version:**

all
**Environment, CPU architecture, OS, and Version:**

all
**Describe the bug**

~/.continue/config.py dont exist only config.json related to continue integration in linux with vscode [https://github.com/mudler/LocalAI/tree/master/examples/continue](https://github.com/mudler/LocalAI/tree/master/examples/continue)
**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

**Comment by lunamidori5** [comment]
@mudler they changed the way continue works, it now uses a GUI inside of VScode to set up the models.

**Comment by golgeek** [comment]
They moved to a json config file (in `~/.continue/continue.json`).

This json would be the equivalent of the outdated example to make it work with LocalAI:
```
{
  "tabAutocompleteModel": {
      "title": "localai",
      "provider": "openai",
      "model": "gpt-3.5-turbo",
      "apiKey": "my-api-key",
      "apiBase": "http://localhost:8080/v1"
  },
  "models": [
    {
        "title": "localai",
        "provider": "openai",
        "model": "gpt-3.5-turbo",
        "apiKey": "my-api-key",
        "apiBase": "http://localhost:8080/v1"
    }
  ],
  "customCommands": [],
  "contextProviders": [
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "open",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ]
}
```

**Comment by golgeek** [comment]
Yeah, I just quickly dumped my config.json file in here because I to much things going on to open a PR right now.

Will do later today if nobody does it before.

**Comment by olariuromeo** [comment]
> Yeah, I just quickly dumped my config.json file in here because I have too much things going on to open a PR right now.
> 
> Will do later today if nobody does it before.

I already tried but it keeps not finding grpc backend while anytingllm works perfectly with the same model

**Comment by lunamidori5** [comment]
@olariuromeo Continue does a great job on keeping their docs up to date, please check them out - https://continue.dev/docs/reference/Model%20Providers/openai

**Comment by lunamidori5** [comment]
(miss clicked)
