### ISSUE TITLE
all-in-one image

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#1855]
A pre-configured image with all the LocalAI settings to have a fully configured instance, for image gen, text gen, text to audio, audio to text, etc. #1373 

Should be used by the #1769, which should automatically select the correct image by the user HW capability:

- [x] CPU image
- [x] CUDA image
- [ ] Intel image
- [ ] Hipblas

**Comment by mudler** [comment]
What is required next: bigger-sized GPU image detection

**Comment by sbe-arg** [comment]
Nice... Where is the documentation or how tos?

**Comment by mudler** [comment]
> Nice... Where is the documentation or how tos?

Not yet in, will work on that prior to the next release
