### ISSUE TITLE
“runtime error: invalid memory address or nil pointer dereference” happened,when i send test prompt to cublas-cuda12-core

### ISSUE THREAD

**Issue by testKKP** [mudler/LocalAI#1861]
**LocalAI version:**

localai:v2.10.0

**Environment, CPU architecture, OS, and Version:**

windows 11，11th Gen Intel(R) Core(TM) i9-11900K ，NVDIA RTX3090
**Describe the bug**

i just run the command "docker run -ti -p 8080:8080 --gpus all localai/localai:v2.10.0-cublas-cuda12-core mixtral-instruct"  exactly the same as the offical website and it setup correctlly. I got correct response to see the mixtral-instruct model have started up.but when i try the command "curl http://localhost:8080/v1/completions -H "Content-Type: application/json" -d "{ \"model\": \"mixtral-instruct\", \"prompt\": \"How are you doing?\" }""  it response {"error":{"code":500,"message":"runtime error: invalid memory address or nil pointer dereference","type":""}}
**To Reproduce**

**Expected behavior**

really hope it can run normally.
**Logs**

the log in docker shows there were nothing wrong happened.
**Additional context**

**Comment by mudler** [comment]
thanks for the issue, there is a v2.10.1 which contains #1853 that fixes the issue above
