### ISSUE TITLE
Dockerhub images referenced in the documentation don't exist

### ISSUE THREAD

**Issue by di-rse** [mudler/LocalAI#1898]
The following images, referenced in the docs, don't seem to be available on dockerhub:

localai/localai:v2.10.1-aio-cpu
localai/localai:v2.10.1-aio-gpu-cuda-11
localai/localai:v2.10.1-aio-gpu-cuda-12
localai/localai:latest-aio-cpu
localai/localai:latest-aio-gpu-cuda12

**Comment by sidewaysthought** [comment]
Confirmed, tried multiple commands to deploy and asked Copilot for a sanity check.

**Comment by kevinraymond** [comment]
Definitely some doc updates needed; if you're looking around in the mean time, here are the images currently available related to the 2.11.0 AIO release:

https://hub.docker.com/r/localai/localai/tags?page=1&name=v2.11.0-aio

**Comment by mudler** [comment]
Closing as this is solved by now and all CI pipelines seems to be functional
