### ISSUE TITLE
can we build non avx cpu aio images?

### ISSUE THREAD

**Issue by sbe-arg** [mudler/LocalAI#1916]
I run this on a docker swarm cluster at "home" and a few of the "servers" are xeons without avx support. Still runs perfectly but have to build on start and takes ~20min each up command. It might help a lot of folks on a budget

**Comment by mudler** [comment]
related to #1888

**Comment by mudler** [comment]
Next releases should have all the variants ( handled in #2232 ) 👍

**Comment by sbe-arg** [comment]
Amazing

**Comment by chris-hatton** [comment]
@sbe-arg Probably smart; I'm struggling to find *any* LLM inference solution that will work on a non-AVX machine!
