### ISSUE TITLE
feat(llama-cpp): support token count

### ISSUE THREAD

**Issue by countzero** [mudler/LocalAI#1920]
**LocalAI version:**
https://github.com/mudler/LocalAI/releases/tag/v2.11.0

**Environment, CPU architecture, OS, and Version:**
CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

**Describe the bug**
The `/chat/completions` API endpoint always returns the value `0` in the properties `completion_tokens`, `prompt_tokens` and `total_tokens`.

**To Reproduce**
Make a POST request against the `/chat/completions` API endpoint.

**Expected behavior**
The `usage` object should be compatible with the OpenAI API and contain specific values regarding the number of processed tokens, so that a consuming client can calculate the tokens / second metric.

**Logs**

Example response:
``` JSON
{
   "choices" : [
      {
         "finish_reason" : "stop",
         "index" : 0,
         "message" : {
            "content" : "I am functioning well, thank you for asking! How can I assist you today?",
            "role" : "assistant"
         }
      }
   ],
   "created" : 1711632671,
   "id" : "d327de7e-f249-4438-94b5-952de5cb241f",
   "model" : "openchat-3.5-0106.Q5_K_M.gguf",
   "object" : "chat.completion",
   "usage" : {
      "completion_tokens" : 0,
      "prompt_tokens" : 0,
      "total_tokens" : 0
   }
}
```

**Additional context**

OpenAI Documentation: https://platform.openai.com/docs/api-reference/chat/object#chat/object-usage

**Comment by AlexM4H** [comment]
I noticed the same error

**Comment by joshSi** [comment]
Looking at source, it may be a feature flag disabled by default?https://github.com/mudler/LocalAI/blob/3c778b538aee121543ddaeb334cbb7f0e4790d98/core/backend/llm.go#L82-L84

**Comment by countzero** [comment]
@joshSi Nice... took some time to find out how to use the feature flags, since they seem not to be documented?!

I changed my `openchat-3.5-0106.Q5_K_M.gguf.yaml` to the following:

```YAML
name: openchat-3.5-0106.Q5_K_M.gguf
backend: llama-cpp

# https://github.com/mudler/LocalAI/issues/1920
feature_flags:
  usage: true

parameters:
  model: openchat-3.5-0106.Q5_K_M.gguf
  max_tokens: 1024
  temperature: 0.1

context_size: 8192
threads: 10
gpu_layers: 0

stopwords:
- "</s>"
- "<|end_of_turn|>"
- "GPT4 Correct User:"

roles:
  system: ''
  assistant: 'GPT4 Correct Assistant:'
  user: 'GPT4 Correct User:'

template:

  chat: |
    {{.Input}}
    GPT4 Correct Assistant:

  completion: |
    {{.Input}}
```

And I am now seeing `completion_tokens` and `total_tokens`, but sadly the `prompt_tokens` are still `0`:

```Shell
curl https://localhost/v1/chat/completions \
>     --insecure \
>     --header "Content-Type: application/json" \
>     --header "Authorization: Bearer eyJhbGciOiJ[...]wac" \
>     --data '{
>         "model": "openchat-3.5-0106.Q5_K_M.gguf",
>         "messages": [
>             {
>                 "role": "system",
>                 "content": "You are a helpfull assistant."
>             },
>             {
>                 "role": "user",
>                 "content": "How are you?"
>             }
>         ],
>         "temperature": 0.7
>     }' \
> | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   704  100   363  100   341    115    108  0:00:03  0:00:03 --:--:--   223
{
   "choices" : [
      {
         "finish_reason" : "stop",
         "index" : 0,
         "message" : {
            "content" : "I am functioning well, thank you for asking! How can I help you today?",
            "role" : "assistant"
         }
      }
   ],
   "created" : 1712001640,
   "id" : "fbeac560-fd6d-4c6e-919c-3bc6b6550731",
   "model" : "openchat-3.5-0106.Q5_K_M.gguf",
   "object" : "chat.completion",
   "usage" : {
      "completion_tokens" : 70,
      "prompt_tokens" : 0,
      "total_tokens" : 70
   }
}
```

@mudler Why did you disable the usage feature in https://github.com/mudler/LocalAI/pull/929 and what could be missing to fix the `prompt_tokens` count? It looks as if it was implemented once: https://github.com/mudler/LocalAI/blob/3c778b538aee121543ddaeb334cbb7f0e4790d98/core/backend/llm.go#L92-L95

**Comment by ChristianWeyer** [comment]
We also have to rely on that response data @mudler - thanks!

**Comment by ChristianWeyer** [comment]
FYI:
I just check out the latest commit (https://github.com/mudler/LocalAI/commit/b739cbb86b9734bd62d4f63fad6583cf97059ea5) - and now the feature flag no longer works.

**Comment by mudler** [comment]
> @joshSi Nice... took some time to find out how to use the feature flags, since they seem not to be documented?!
> 
> I changed my `openchat-3.5-0106.Q5_K_M.gguf.yaml` to the following:
> 
> ```yaml
> name: openchat-3.5-0106.Q5_K_M.gguf
> backend: llama-cpp
> 
> # https://github.com/mudler/LocalAI/issues/1920
> feature_flags:
>   usage: true
> 
> parameters:
>   model: openchat-3.5-0106.Q5_K_M.gguf
>   max_tokens: 1024
>   temperature: 0.1
> 
> context_size: 8192
> threads: 10
> gpu_layers: 0
> 
> stopwords:
> - "</s>"
> - "<|end_of_turn|>"
> - "GPT4 Correct User:"
> 
> roles:
>   system: ''
>   assistant: 'GPT4 Correct Assistant:'
>   user: 'GPT4 Correct User:'
> 
> template:
> 
>   chat: |
>     {{.Input}}
>     GPT4 Correct Assistant:
> 
>   completion: |
>     {{.Input}}
> ```
> 
> And I am now seeing `completion_tokens` and `total_tokens`, but sadly the `prompt_tokens` are still `0`:
> 
> ```shell
> curl https://localhost/v1/chat/completions \
> >     --insecure \
> >     --header "Content-Type: application/json" \
> >     --header "Authorization: Bearer eyJhbGciOiJ[...]wac" \
> >     --data '{
> >         "model": "openchat-3.5-0106.Q5_K_M.gguf",
> >         "messages": [
> >             {
> >                 "role": "system",
> >                 "content": "You are a helpfull assistant."
> >             },
> >             {
> >                 "role": "user",
> >                 "content": "How are you?"
> >             }
> >         ],
> >         "temperature": 0.7
> >     }' \
> > | json_pp
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   704  100   363  100   341    115    108  0:00:03  0:00:03 --:--:--   223
> {
>    "choices" : [
>       {
>          "finish_reason" : "stop",
>          "index" : 0,
>          "message" : {
>             "content" : "I am functioning well, thank you for asking! How can I help you today?",
>             "role" : "assistant"
>          }
>       }
>    ],
>    "created" : 1712001640,
>    "id" : "fbeac560-fd6d-4c6e-919c-3bc6b6550731",
>    "model" : "openchat-3.5-0106.Q5_K_M.gguf",
>    "object" : "chat.completion",
>    "usage" : {
>       "completion_tokens" : 70,
>       "prompt_tokens" : 0,
>       "total_tokens" : 70
>    }
> }
> ```
> 
> @mudler Why did you disable the usage feature in #929 and what could be missing to fix the `prompt_tokens` count? It looks as if it was implemented once:
> 
> https://github.com/mudler/LocalAI/blob/3c778b538aee121543ddaeb334cbb7f0e4790d98/core/backend/llm.go#L92-L95

that didn't disable the feature at all - it just put the feature behind a flag as it was experimental

> FYI: I just check out the latest commit ([b739cbb](https://github.com/mudler/LocalAI/commit/b739cbb86b9734bd62d4f63fad6583cf97059ea5)) - and now the feature flag no longer works.

The feature was working with `-ggml` based models. For `gguf` this stopped working as we moved away from the precedent implementation with golang bindings. 

This needs now to be implemented (from scratch) in the new backend to have back the token count.

**Comment by mudler** [comment]
I've opened up https://github.com/mudler/LocalAI/pull/2035 that should add now the token count with llama.cpp without needing to enable that experimental feature flag

**Comment by countzero** [comment]
@mudler Thank you, works like a charm!
