### ISSUE TITLE
Issue with Function Calls repeating incorrectly in AIO docker image with CUDA support.

### ISSUE THREAD

**Issue by jesst3r** [mudler/LocalAI#1950]
_**Greetings! 
First of all, I'd like to extend my sincerest thanks to @mudler for creating such remarkable software ❤️. 
Unfortunately, however, I have encountered an issue with the agent's function calling feature, described below.**_

### **LocalAI version:**
_localai/localai:latest-aio-gpu-nvidia-cuda-12_

### **Environment, CPU architecture, OS, and Version:**
_Intel Core i9-9900K @ 3.60GHz, Win 11, x2 3090TI (48 Gb VRAM in total), 64Gb RAM_

### **Describe the bug**

When using the latest Docker image - AIO (with CUDA support), the function calls do not work as expected. The AI model (using the default "Nous Hermes" model) repeatedly calls various functions out of context, regardless of various input messages, seeming to ignore them or simply parroting back the input. I have already experimented with various temperature settings, ranging from 1.0 down to 0.1, but the issue persists. The funniest part is that it writes its responses to the user in function calls.  (as you can see on the picture below)
_(PSST: I believe this is a general issue. It doesn't depend on whether CUDA is present or not)_

![vffOJB4tYB](https://github.com/mudler/LocalAI/assets/331591/ca886cb3-54b8-480e-b022-6a8363fe3956)

https://github.com/mudler/LocalAI/assets/331591/a4efe27e-6535-48b2-8ac8-8cbe45364ffe

### **To Reproduce**
1. Deploy the latest Docker image AIO with CUDA support.
2. Start a conversation with the AI model using the Nous Hermes model (Mistral 7B).
3. During the dialogue, enter a basic interaction such as asking "How r u? :)", and provide appropriate tools array.
4. Observe the AI's behavior as it incorrectly triggers the provided functions (Irrelevant to the tool_choice setting).
5. Attempt varying temperature settings from 1.0 to 0.1 does not alter the erroneous behavior. 

### **Expected behavior**
The assistant should intelligently determine when to call a particular function based on the given context of the user interaction. It should recognize and process different types of messages appropriately, initiating function calls only when the conversation logically requires it. The function calling mechanism should be dynamic and context-aware, avoiding repetitive or irrelevant calls, and should not resort to merely echoing the user's inputs. Function calls should be a seamless part of the conversation flow, enhancing the assistant's responses and overall user experience. 

Additionally, the AI should maintain a coherent and contextually appropriate dialogue, demonstrating an understanding of the user's queries and statements before deciding to invoke any function. If a function call is not warranted, the AI should continue the conversation naturally, without unnecessarily triggering API calls or searches.

**Comment by osdio** [comment]
I met the same issue.
