### ISSUE TITLE
The stores link on https://localai.io/ is broken

### ISSUE THREAD

**Issue by SuperPat45** [mudler/LocalAI#1986]
The stores link on https://localai.io/#-features is broken

The link opens the nonexistent page:
https://localai.io/features/stores
The page is located at:
https://localai.io/stores/

**Comment by mudler** [comment]
@SuperPat45 where exactly did you find the broken links? can you file a PR?

**Comment by SuperPat45** [comment]
![image](https://github.com/mudler/LocalAI/assets/7791600/4290e134-2af4-4b3a-be50-45d4f1ea5672)
