### ISSUE TITLE
Please support reranker API

### ISSUE THREAD

**Issue by thiner** [mudler/LocalAI#2018]
**Is your feature request related to a problem? Please describe.**
Nowadays, embedding + reranker is the SOTA solution to improve the accuracy of RAG system. We've already have the embedding API support in LocalAI, it would be a big step forward if we can support reranker API.

**Describe the solution you'd like**
There are many reranker models out there, some famous names: `bce-reranker-base_v1`, `CohereRerank`, `bge-reranker-v2-m3`. I think the Jina reranker API would be a good format to implement. https://jina.ai/reranker/#apiform

**Describe alternatives you've considered**
n/a

**Additional context**
The benchmark regarding embedding+reranker for RAG:
![](https://github.com/netease-youdao/BCEmbedding/raw/master/Docs/assets/rag_eval_multiple_domains_summary.jpg)

**Comment by thiner** [comment]
I spent some time trying to figure out how to implement. Below are my workouts:

1. Use reranker model is as easy as using embedding model. Below is the example of `bce-reranker-base-v1`.
```python
from sentence_transformers import CrossEncoder

# init reranker model
model = CrossEncoder('maidalun1020/bce-reranker-base_v1', max_length=512)

# calculate scores of sentence pairs
scores = model.predict(sentence_pairs)
```
2. `backend/python/sentencetransformers/sentencetransoformers.py` supports embedding already, maybe add one more `Rerank` method with above code is enough. The major work would be refactor protobuf and API component.

**Comment by mudler** [comment]
having a quick look at this - let's see if can get something working before the weekend

**Comment by mudler** [comment]
![output](https://github.com/mudler/LocalAI/assets/2420543/ede67b25-fac4-4833-ae4f-78290e401e60)

ok that was easy enough - going to open up a PR soon

**Comment by mudler** [comment]
@thiner will be part of the next release - if you want to test out before that, PR is at https://github.com/mudler/LocalAI/pull/2121

**Comment by thiner** [comment]
@mudler How can I attach the reranker feature to `cublas-cuda12-core` image? I tried to do so in Dockerfile: `RUN make BUILD_TYPE=cublas -C backend/python/rerankers`, but failed due to below error:
```
0.189 make: Entering directory '/build/backend/python/rerankers'
0.189 python3 -m grpc_tools.protoc -I../.. --python_out=. --grpc_python_out=. backend.proto
0.189 make: Leaving directory '/build/backend/python/rerankers'
0.189 /opt/conda/bin/python3: Error while finding module specification for 'grpc_tools.protoc' (ModuleNotFoundError: No module named 'grpc_tools')
0.189 make: *** [Makefile:27: backend_pb2.py] Error 1
```
What should I do to fix?

**Comment by BradKML** [comment]
@mudler thank you for the cross-link references since I was mostly focused on LiteLLM and Ollama for maximizing compatibility, but knowing that LocalAI is "getting there" is quite a relief

**Comment by mudler** [comment]
> ~@mudler How can I attach the reranker feature to `cublas-cuda12-core` image? I tried to do so in Dockerfile: `RUN make BUILD_TYPE=cublas -C backend/python/rerankers`, but failed due to below error:~
> 
> ```
> 0.189 make: Entering directory '/build/backend/python/rerankers'
> 0.189 python3 -m grpc_tools.protoc -I../.. --python_out=. --grpc_python_out=. backend.proto
> 0.189 make: Leaving directory '/build/backend/python/rerankers'
> 0.189 /opt/conda/bin/python3: Error while finding module specification for 'grpc_tools.protoc' (ModuleNotFoundError: No module named 'grpc_tools')
> 0.189 make: *** [Makefile:27: backend_pb2.py] Error 1
> ```
> 
> ~What should I do to fix?~
> 
> **Please forgive me for my lazy thinking, the solution is quite straightforward, `pip install grpcio-tools`.**

I'd suggest you to use non-core images. If you want to use the core images still, you can or either create a Dockerfile based on top of it and run the command to prepare the backend, or use `EXTRA_BACKENDS`, as outlined in the docs here:

https://localai.io/advanced/#extra-backends

**Comment by thiner** [comment]
Yes, I did so. The docker image is created successfully by specifying the extra nackend. But I got the groc error at runtime still. Is there any changes to grpc module in this v2.13.0 release? I built the autogptq image with this dockerfile previousely, and that's working.
