### ISSUE TITLE
[Feature Request] - GPT-Researcher

### ISSUE THREAD

**Issue by HyperCriSiS** [mudler/LocalAI#2112]
I think this Tool would be a great addition to LocalAI
:)

It can be configured to use a local LLM and any search engine. 

GPT Researcher is an autonomous agent designed for comprehensive online research on a variety of tasks.

The agent can produce detailed, factual and unbiased research reports, with customization options for focusing on relevant resources, outlines, and lessons. Inspired by the recent Plan-and-Solve and RAG papers, GPT Researcher addresses issues of speed, determinism and reliability, offering a more stable performance and increased speed through parallelized agent work, as opposed to synchronous operations.

https://github.com/assafelovic/gpt-researcher

**Comment by jtwolfe** [comment]
I expect that this is not within the scope of the localai project.
GPT-Researcher it appears can be configured already to make use of self hosted models so this would just be a matter of configuration.
There is usually an `OPENAI_BASE_URL` variable that can be set to `http://localhost:8080/v1` (or the like) in these apps, you can set the api key to `dummy` and that should work. if you have 'model' issues like i did for chat-dev the workaround is to find the name of the model that the tool is using aka `gpt-3.5-turbo-1106` and change the name of the model you want to use in the .yaml file and that should satisfy the tool. 
be aware that response time for api queries is also often limited to 60s for these sorts of tools, this should be configurable within the tools source
