### ISSUE TITLE
missing nvidia-smi disable gpu support

### ISSUE THREAD

**Issue by virdb** [mudler/LocalAI#2117]
**LocalAI version:**
 latest-aio-gpu-nvidia-cuda-12 
**Environment, CPU architecture, OS, and Version:**
kubernetes k0s 1.29.4 on ubuntu 22.04
**Describe the bug**
running the image in a pod on a gpu enabled node, i got:
```
 ===> LocalAI All-in-One (AIO) container starting...
NVIDIA GPU detected
/aio/entrypoint.sh: line 52: nvidia-smi: command not found
NVIDIA GPU detected, but nvidia-smi is not installed. GPU acceleration will not be available.
GPU acceleration is not enabled or supported. Defaulting to CPU.
```

**To Reproduce**
run a pod with the image on a gpu-enabled node

**Expected behavior**
gpu support is enabled anyway and/or nvidia-smi is included

**Logs**
 see up

**Additional context**
-

**Comment by lunamidori5** [comment]
ISSUE fixed on discord via support from @cryptk thank you!

**Comment by mudler** [comment]
would be helpful for reference to share the fix here if someone else is looking at the bug - what was the issue at the end?

**Comment by virdb** [comment]
Missing `runtimeClassName: nvidia` in the pod spec
