### ISSUE TITLE
2.13.0 failes to build caused by missing path pkg/grpc/proto

### ISSUE THREAD

**Issue by ck3d** [mudler/LocalAI#2135]
The latest version 2.13.0 of LocalAI references pkg/grpc/proto of LocalAI in following file:
https://github.com/mudler/LocalAI/blob/master/core/backend/llm.go#L17C32-L17C46

The path is not available, therefor the build failes with following error:

    github.com/go-skynet/LocalAI/pkg/grpc/proto: no matching versions for query "latest"

**LocalAI version:** 2.13.0

**Comment by dave-gray101** [comment]
The files in that folder _should_ be generated during the build. Can you post the full build logs in case there's a failure earlier up?

**Comment by ck3d** [comment]
I package LocalAI as Nix package. The go modules are a separate package and built upfront.

Thanks to your hint, I found make target protogen-go, which generates the files. I have to add this target for the go modules package.
