### ISSUE TITLE
Incorrect version causing formatting issue in docs

### ISSUE THREAD

**Issue by linuxtek-canada** [mudler/LocalAI#2162]
**LocalAI version:**
v2.13.0

**Environment, CPU architecture, OS, and Version:**
N/A - Docs Issue

**Describe the bug**
The current version being used in the OpenAI Docs is "🖼️ v2.13.0 - Model gallery edition".  This is being pulled from:
https://github.com/mudler/LocalAI/blob/master/docs/data/version.json

The docs use a `{{< version >}}` dynamic value referencing the above json file.

This is causing all the Docker commands to have the emoji and incorrect values in them here:
https://localai.io/docs/getting-started/run-other-models/

**To Reproduce**
Copy the Docker command from the [Run Other Models](https://localai.io/docs/getting-started/run-other-models/) Docs page, and attempt to run it.  You will get this error:

```
docker run -ti -p 8080:8080 localai/localai: :frame_photo: v2.13.0 - Model gallery edition-ffmpeg-core phi-2
docker: invalid reference format.
See 'docker run --help'.
```

**Expected behavior**
Correct Docker syntax with proper image names and tags to pull the image properly.

**Logs**
N/A

**Additional context**
Based on the [file history](https://github.com/mudler/LocalAI/commits/master/docs/data/version.json), the version should just be v2.13.0.

**Comment by linuxtek-canada** [comment]
I can work on fixing this tomorrow.

**Comment by debjit** [comment]
Thanks @linuxtek-canada for raising this issue. 
https://discord.com/channels/1096914990004457512/1233965318100094996/1233965325851168799

**Comment by linuxtek-canada** [comment]
This is fixed via this commit: https://github.com/mudler/LocalAI/commit/3179c019af17a7fdede8089eaa410359ca151d74

Confirmed the website is already corrected.
