### ISSUE TITLE
OpenVINO on Arc A770 exception `Check 'written_size == size' `

### ISSUE THREAD

**Issue by richiejp** [mudler/LocalAI#2210]
c.c @fakezeta 
**LocalAI version:**
quay.io/go-skynet/local-ai@sha256:4e4e427433285b056f32bfaa313ec0e75aeacb5b5c8c273953f9d2242fb55a60

**Environment, CPU architecture, OS, and Version:**

Linux dell 6.5.0-1020-oem #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Apr  3 14:54:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**

When I restrict a Pod to my A770 I get an exception, more details on the setup in #2208 

**Logs**

```
10:36AM DBG GRPC(fakezeta/llama-3-8b-instruct-ov-int8-127.0.0.1:33205): stderr Error: Exception from src/inference/src/cpp/core.cpp:106:
10:36AM DBG GRPC(fakezeta/llama-3-8b-instruct-ov-int8-127.0.0.1:33205): stderr Check 'written_size == size' failed at src/plugins/intel_gpu/include/intel_gpu/graph/serialization/binary_buffer.hpp:25:
10:36AM DBG GRPC(fakezeta/llama-3-8b-instruct-ov-int8-127.0.0.1:33205): stderr [GPU] Failed to write 58720256 bytes to stream! Wrote 2727448
10:36AM DBG GRPC(fakezeta/llama-3-8b-instruct-ov-int8-127.0.0.1:33205): stderr
10:36AM DBG GRPC(fakezeta/llama-3-8b-instruct-ov-int8-127.0.0.1:33205): stderr
10:36AM ERR Server error error="could not load model (no success): Unexpected err=RuntimeError(\"Exception from src/inference/src/cpp/core.cpp:106:\\nCheck 'written_size == size' failed at src/plugins/intel_gpu/include/intel_gpu/graph/serialization/binary_buffer.hpp:25:\\n[GPU] Failed to write 58720256 bytes to stream! Wrote 2727448\\n\\n\"), type(err)=<class 'RuntimeError'>" ip=127.0.0.1 latency=20.027449511s method=POST status=500 url=/v1/chat/completions
```

**Additional context**

I haven't got much to work with the A770 yet.

**Comment by fakezeta** [comment]
Hi @richiejp, 

I replicated the error:
```
RuntimeError: Exception from src/inference/src/cpp/core.cpp:106:
Check 'written_size == size' failed at src/plugins/intel_gpu/include/intel_gpu/graph/serialization/binary_buffer.hpp:25:
[GPU] Failed to write 9437184 bytes to stream! Wrote 5800777
```

It triggers when there is not enough disk space when compiling the model for the selected device.
Have you checked that there is enough disk space? 
I know that it's like asking to someone if he has gasoline in the car when it is not starting, and I feel stupid to ask but anyway it's worth to check. 😄
