### ISSUE TITLE
WebUI: 'Authorization header missing'

### ISSUE THREAD

**Issue by AlexM4H** [mudler/LocalAI#2227]
The WebUI is making great progress. Many thanks for that. 

I tried to test the chat today. Without using an API-KEY in my settings it works fine. 

But how can I enter the API-KEY from my settings into the WebUI? The input option is only displayed if I have not set such a KEY. 

If a API-KEY is set in my environment settings, I get the error message 

`{"message": "Authorization header missing"}`

EDIT:

`curl -X GET "https://localai/v1/models" -H "Authorization: Bearer sk-my-api-key"|jq`

works with the correct key, otherwise "Invalid API key"

**Comment by AlexM4H** [comment]
Thanks for your workaround. I use ModHeader instead. It works well.

**Comment by Jordanb716** [comment]
I have this issue as well. Using the latest Docker image (v2.15.0-cublas-cuda12-ffmpeg), if $LOCALAI_API_KEY is set I only get "Authorization header missing" when I try to access the webui. Works perfectly if not set.

**Comment by AlexM4H** [comment]
Any updates? We have a workaround for this error, but no fix yet.

**Comment by mudler** [comment]
That's not a bug - the WebUI is served by the API and,  does not support specifying an API KEY on the first place for all the calls. 
As it exposes outside confidential informations, it is gated for security purposes by the API_KEY entirely. As @fakezeta mentioned there are browser plugins to prefix calls with a bearer token that can be used to access the webui.

As there is no user authentication, nor the WebUI supports settings API Keys across all the application, the safest route is to put the whole UI behind an API KEY as it could leak sensitive informations.

If you think there is room for improvement, please create a ticket suggesting a solution - but I'm not really into plugging a user/auth system to LocalAI. We can think to have the WebUI to setup the token when accessed at first, but that's an enhancement, not a bug.

**Comment by mintyleaf** [comment]
@mudler 
do you aware that p2p diagnostics functionality is suppressed when api keys is used?
