### ISSUE TITLE
UI: Model Gallery: indicate trust_remote_code

### ISSUE THREAD

**Issue by dave-gray101** [mudler/LocalAI#2250]
Absolutely nothing against @fakezeta , but when I saw #2249 it occurred to me that we need to be indicating to users somehow in the model gallery user interface routes which models have `trust_remote_code` on, as that's a distinct security difference that may matter to some people.

I think we just need to add some code to core/http/routes/ui.go to check for that specific property on a model, and add a css class of some type if so.

**Comment by dave-gray101** [comment]
(Bug tagged because I consider this a security flaw?)

**Comment by fakezeta** [comment]
I agree with @dave-gray101: In the meanwhile I can add the tag `Remote Code Enabled`.

What do you think of it as a workaround?

**Comment by dave-gray101** [comment]
I created this issue because I don't think that this is even worth holding your PR up - it's something that needs to get added before the gallery grows too large to fix it with stuff like that :)

**Comment by fakezeta** [comment]
But I completely agree with you. 
Sadly Phi-3 requires this flag and downloads the file [`configuration_phi3.py`](https://huggingface.co/microsoft/Phi-3-mini-128k-instruct/raw/main/configuration_phi3.py) directly from HF.
It has the Model Configuration code and the Rope Scaling validation (this is how it reaches 128k of context).

By the way I'm too tired today and Yaml got my head.
