### ISSUE TITLE
Loading UI produces an error on M3 MBP

### ISSUE THREAD

**Issue by michaelmior** [mudler/LocalAI#2257]
**LocalAI version:**
Commit d1e3436de51eac40843b9f8ce5556fce5ab5716d

**Environment, CPU architecture, OS, and Version:**

Darwin GCIS-MJMVCS-RM1 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:37 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6031 arm64

**Describe the bug**

Unable to access the UI

**To Reproduce**

```
$ make build
$ ./localai run
```
Open http://localhost:8080 in browser

**Expected behavior**

I expected to see the UI, but I get an error instead. Using the API works correctly.

**Logs**

No error in the logs other the message which gets returned when I try to load the UI.

```json
{
"error": {
"code": 500,
"message": "failed to render: template: views/index:36:39: executing \"views/index\" at <$cfg.Icon>: nil pointer evaluating *gallery.Config.Icon",
"type": ""
}
}
```

**Comment by michaelmior** [comment]
The error message is given in the original issue. No recent changes as this is a fresh install.

**Comment by mudler** [comment]
@michaelmior good catch, there is a bug in the index page and going to fix it soon - however tagged releases shouldn't be affected.
