### ISSUE TITLE
openvoice v1 and v2 now MIT licensed, let local ai support them

### ISSUE THREAD

**Issue by hlzhangxt** [mudler/LocalAI#2300]
**Is your feature request related to a problem? Please describe.**

The now the Amy TTS voice is like a robot, OpenVoice is better.

**Describe the solution you'd like**

Integrate the openvoice.
**Describe alternatives you've considered**

https://github.com/myshell-ai/OpenVoice/blob/main/docs/USAGE.md#openvoice-v2
**Additional context**

https://github.com/myshell-ai/OpenVoice/blob/main/docs/USAGE.md#openvoice-v2

**Comment by mudler** [comment]
yep that is actually in the radar #1126
