### ISSUE TITLE
Distributed Llama.cpp Inferencing option `llamacpp-worker` not working

### ISSUE THREAD

**Issue by sestren** [mudler/LocalAI#2469]
**LocalAI version:**

LocalAI v2.16.0
Docker Image ID: f82868278773 / TAG: latest-aio-cpu

**Environment, CPU architecture, OS, and Version:**

```
uname -a: Linux XXX 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Xeon(R) CPU D-1521 @ 2.40GHz
RAM: 16 GB
```

**Describe the bug**

When running `local-ai llamacpp-worker <listening_address> <listening_port>`, local-ai tries to load `llamacpp-worker`, `<listening_address>` and `<listening_port>` as model instead of starting the localai llamacpp-worker.

**To Reproduce**

Pull latest latest-aio-cpu image and run it with the `llamacpp-worker` option
Alternatively, start bash terminal inside the container using `docker exec -it local-ai /bin/bash` and run the command `./local-ai llamacpp-worker 0.0.0.0 123445`

**Expected behavior**

Should be able to start workers to offload the computation when running:
```
local-ai llamacpp-worker <listening_address> <listening_port>
```

**Logs**

```
root@7aadfbf3f809:/build# ./local-ai llamacpp-worker 0.0.0.0 123445
9:59PM INF loading environment variables from file envFile=.env
9:59PM INF Setting logging to info
9:59PM INF Starting LocalAI using 8 threads, with models path: /build/models
9:59PM INF LocalAI version: v2.16.0 (e0187c2a1a4cde837398ada217d0ad161b7976d6)
9:59PM WRN [startup] failed resolving model 'llamacpp-worker'
9:59PM WRN [startup] failed resolving model '0.0.0.0'
9:59PM WRN [startup] failed resolving model '123445'
9:59PM INF Preloading models from /build/models
```

**Additional context**

Trying Distributed Llama.cpp Inferencing after v2.16 release notes

**Comment by nickp27** [comment]
I think this is actually an issue with the docs, rather than a bug itself. The correct way to initiate it which I have working is ./localai worker llamacpp-worker (or the p2p) equivalent.

I have it working in docker-compose and can post that when I get home.

Just waiting for my PR in llama.cpp which merged last night to be available in localai to enable sycl on the rpc workers

**Comment by nickp27** [comment]
> I think this is actually an issue with the docs, rather than a bug itself. The correct way to initiate it which I have working is ./localai worker llamacpp-worker (or the p2p) equivalent.
> 
> I have it working in docker-compose and can post that when I get home.
> 
> Just waiting for my PR in llama.cpp which merged last night to be available in localai to enable sycl on the rpc workers

This is my docker-compose for my worker in case it helps (I have been tested both the p2p and non-p2p options) and its working, although CPU back-end on my small homelab cluster just isnt good:

```
    local-ai-worker:
        container_name: localai-worker
        tty: true
        stdin_open: true
        devices:
            - /dev/dri/renderD128:/dev/dri/renderD128
        restart: always
        environment:
            - DEBUG=true
            - MODELS_PATH=/models
            - THREADS=8
            - SINGLE_ACTIVE_BACKEND=false
            - GGML_SYCL_DEVICE=0
            - WATCHDOG_BUSY=true
            - WATCHDOG_BUSY_TIMEOUT=15m
            - ZES_ENABLE_SYSMAN=1
            - LD_PRELOAD=/opt/intel/oneapi/compiler/2024.1/lib/libiomp5.so
            - OMP_NUM_THREADS=8
            - TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXX
        volumes:
            - ./models:/models
#            - ./images:/tmp/generated/images/
        entrypoint:
           - /build/entrypoint.sh
           - worker
           - p2p-llama-cpp-rpc
#           - llama-cpp-rpc
#           - localai-worker:42583
        image: quay.io/go-skynet/local-ai:master-sycl-f16-ffmpeg
        privileged: true
        network_mode: host
```
