### ISSUE TITLE
coqui tts: change to better maintained fork 

### ISSUE THREAD

**Issue by blob42** [mudler/LocalAI#2513]
The coqui tts currently used has been unmaintained since some time. It seems [this repo](https://github.com/idiap/coqui-ai-TTS) is the new maintained fork that is taking over. It is this fork that powers the [RealtimeTTS library](https://github.com/KoljaB/RealtimeTTS) library. 

It would also be great to add support for the [RealtimeTTS engine](https://github.com/KoljaB/RealtimeTTS). I would be glad to make a PR for both.

**Comment by dave-gray101** [comment]
I think this is a great idea!


FYI: the existing extra-coqui test can be a bit flaky, and tends to need repeats sometimes. It's potentially related to being old as you say... or there may be something iffy with the code itself to keep an eye out for.

**Comment by mudler** [comment]
good point indeed! now that coqui is off the table pointing to a maintained version would be much wanted and better  :+1:

**Comment by AlexM4H** [comment]
BTW: The fork at https://github.com/idiap/coqui-ai-TTS is 198 commits ahead of coqui-ai/TTS
