### ISSUE TITLE
API appears to hang forever if a response is interrupted

### ISSUE THREAD

**Issue by Mithrillion** [mudler/LocalAI#2526]
**LocalAI version:**
quay.io/go-skynet/local-ai:v2.16.0-cublas-cuda12

**Environment, CPU architecture, OS, and Version:**
OS: openSUSE Tumbleweed x86_64
Kernel: 6.9.3-1-default
CPU: AMD Ryzen 9 3950X (32) @ 3.500GHz
GPU: NVIDIA GeForce RTX 3090
NVIDIA-SMI 550.90.07

**Describe the bug**
It appears if a llamacpp model is configured and loaded, and during a message generation, the client side interrupts the generation, it results in a `DBG Sending chunk failed: connection closed` message, and all subsequent requests to the model will fail. The debug message shows that `DBG Model already loaded in memory` but no further processing will happen.

**To Reproduce**
1. Set up a custom model in LocalAI (e.g. a GGUF model from HuggingFace.
2. Configure a chat UI like LibreChat to use LocalAI API, or use LocalAI's chat tab
3. Start generating a message
4. Interrupt during generation (e.g. using "stop" button, or switch out of LocalAI's chat tab and back again)
5. Attempt to continue generation, generate a new message, or use the same model in LocalAI's "chat" tab

**Expected behavior**
LocalAI should be able to continue generating a message or reply to new messages after a client-side interruption

**Logs**
`api-1  | 4:09AM DBG Sending chunk: {"created":1717906124,"object":"chat.completion.chunk","id":"8f381d3b-5916-402f-81f4-f64b8b496f6a","model":"Psyonic-Cetacean-Ultra-Quality-20b-Q8_0","choices":[{"index":0,"finish_reason":"","delta":{"content":"e"}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
api-1  | 
api-1  | 4:09AM DBG Sending chunk: {"created":1717906124,"object":"chat.completion.chunk","id":"8f381d3b-5916-402f-81f4-f64b8b496f6a","model":"Psyonic-Cetacean-Ultra-Quality-20b-Q8_0","choices":[{"index":0,"finish_reason":"","delta":{"content":" "}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
api-1  | 
api-1  | 4:09AM DBG Sending chunk failed: connection closed
api-1  | 4:09AM DBG Request received: {"model":"Psyonic-Cetacean-Ultra-Quality-20b-Q8_0","language":"","n":0,"top_p":1,"top_k":null,"temperature":1,"max_tokens":null,"echo":false,"batch":0,"ignore_eos":false,"repeat_penalty":0,"n_keep":0,"frequency_penalty":0,"presence_penalty":0,"tfz":null,"typical_p":null,"seed":null,"negative_prompt":"","rope_freq_base":0,"rope_freq_scale":0,"negative_prompt_scale":0,"use_fast_tokenizer":false,"clip_skip":0,"tokenizer":"","file":"","response_format":{},"size":"","prompt":null,"instruction":"","input":null,"stop":null,"messages":[{"role":"user","content":"write a story about a castle siege"},{"role":"assistant","content":"Once upon a time, in a kingdom far away, there stood a majestic castle nestled on a hill overlooking the vast countryside. The castle was th"}],"functions":null,"function_call":null,"stream":true,"mode":0,"step":0,"grammar":"","grammar_json_functions":null,"grammar_json_name":null,"backend":"","model_base_name":""}
api-1  | 4:09AM DBG Configuration read: &{PredictionOptions:{Model:Psyonic-Cetacean-Ultra-Quality-20b-Q8_0.gguf Language: N:0 TopP:0xc00052f978 TopK:0xc00061f088 Temperature:0xc00052f970 Maxtokens:0xc00061f0c0 Echo:false Batch:0 IgnoreEOS:false RepeatPenalty:0 Keep:0 FrequencyPenalty:0 PresencePenalty:0 TFZ:0xc00061f0b8 TypicalP:0xc00061f0b0 Seed:0xc00061f0d8 NegativePrompt: RopeFreqBase:0 RopeFreqScale:0 NegativePromptScale:0 UseFastTokenizer:false ClipSkip:0 Tokenizer:} Name:Psyonic-Cetacean-Ultra-Quality-20b-Q8_0 F16:0xc00061f050 Threads:0xc00061f048 Debug:0xc00052fa70 Roles:map[assistant:ASSISTANT: system:SYSTEM: user:USER:] Embeddings:false Backend:llama TemplateConfig:{Chat:{{.Input}}
api-1  | <|im_start|>assistant
api-1  |  ChatMessage:<|im_start|>{{if eq .RoleName "assistant"}}assistant{{else if eq .RoleName "system"}}system{{else if eq .RoleName "user"}}user{{end}}
api-1  | {{if .Content}}{{.Content}}{{end}}<|im_end|>
api-1  |  Completion:{{.Input}}
api-1  |  Edit: Functions: UseTokenizerTemplate:false JoinChatMessagesByCharacter:<nil>} PromptStrings:[] InputStrings:[] InputToken:[] functionCallString: functionCallNameString: FunctionsConfig:{DisableNoAction:false GrammarConfig:{ParallelCalls:false DisableParallelNewLines:false MixedMode:false NoMixedFreeString:false NoGrammar:false Prefix:} NoActionFunctionName: NoActionDescriptionName: ResponseRegex: JSONRegexMatch:[] ReplaceFunctionResults:[] ReplaceLLMResult:[] FunctionName:false} FeatureFlag:map[] LLMConfig:{SystemPrompt: TensorSplit: MainGPU: RMSNormEps:0 NGQA:0 PromptCachePath: PromptCacheAll:false PromptCacheRO:false MirostatETA:0xc00061f0a8 MirostatTAU:0xc00061f0a0 Mirostat:0xc00061f098 NGPULayers:0xc00061f058 MMap:0xc00061f0d0 MMlock:0xc00061f0d1 LowVRAM:0xc00061f0d1 Grammar: StopWords:[user| assistant| system| <|im_end|> <|im_start|> <s> </s> <unk>] Cutstrings:[] TrimSpace:[] TrimSuffix:[] ContextSize:0xc00061f038 NUMA:false LoraAdapter: LoraBase: LoraScale:0 NoMulMatQ:false DraftModel: NDraft:0 Quantization: GPUMemoryUtilization:0 TrustRemoteCode:false EnforceEager:false SwapSpace:0 MaxModelLen:0 TensorParallelSize:0 MMProj: FlashAttention:false NoKVOffloading:false RopeScaling: ModelType: YarnExtFactor:0 YarnAttnFactor:0 YarnBetaFast:0 YarnBetaSlow:0} AutoGPTQ:{ModelBaseName: Device: Triton:false UseFastTokenizer:false} Diffusers:{CUDA:false PipelineType: SchedulerType: EnableParameters: CFGScale:0 IMG2IMG:false ClipSkip:0 ClipModel: ClipSubFolder: ControlNet:} Step:0 GRPC:{Attempts:0 AttemptsSleepTime:0} VallE:{AudioPath:} CUDA:false DownloadFiles:[] Description: Usage:}
api-1  | 4:09AM DBG Parameters: &{PredictionOptions:{Model:Psyonic-Cetacean-Ultra-Quality-20b-Q8_0.gguf Language: N:0 TopP:0xc00052f978 TopK:0xc00061f088 Temperature:0xc00052f970 Maxtokens:0xc00061f0c0 Echo:false Batch:0 IgnoreEOS:false RepeatPenalty:0 Keep:0 FrequencyPenalty:0 PresencePenalty:0 TFZ:0xc00061f0b8 TypicalP:0xc00061f0b0 Seed:0xc00061f0d8 NegativePrompt: RopeFreqBase:0 RopeFreqScale:0 NegativePromptScale:0 UseFastTokenizer:false ClipSkip:0 Tokenizer:} Name:Psyonic-Cetacean-Ultra-Quality-20b-Q8_0 F16:0xc00061f050 Threads:0xc00061f048 Debug:0xc00052fa70 Roles:map[assistant:ASSISTANT: system:SYSTEM: user:USER:] Embeddings:false Backend:llama TemplateConfig:{Chat:{{.Input}}
api-1  | <|im_start|>assistant
api-1  |  ChatMessage:<|im_start|>{{if eq .RoleName "assistant"}}assistant{{else if eq .RoleName "system"}}system{{else if eq .RoleName "user"}}user{{end}}
api-1  | {{if .Content}}{{.Content}}{{end}}<|im_end|>
api-1  |  Completion:{{.Input}}
api-1  |  Edit: Functions: UseTokenizerTemplate:false JoinChatMessagesByCharacter:<nil>} PromptStrings:[] InputStrings:[] InputToken:[] functionCallString: functionCallNameString: FunctionsConfig:{DisableNoAction:false GrammarConfig:{ParallelCalls:false DisableParallelNewLines:false MixedMode:false NoMixedFreeString:false NoGrammar:false Prefix:} NoActionFunctionName: NoActionDescriptionName: ResponseRegex: JSONRegexMatch:[] ReplaceFunctionResults:[] ReplaceLLMResult:[] FunctionName:false} FeatureFlag:map[] LLMConfig:{SystemPrompt: TensorSplit: MainGPU: RMSNormEps:0 NGQA:0 PromptCachePath: PromptCacheAll:false PromptCacheRO:false MirostatETA:0xc00061f0a8 MirostatTAU:0xc00061f0a0 Mirostat:0xc00061f098 NGPULayers:0xc00061f058 MMap:0xc00061f0d0 MMlock:0xc00061f0d1 LowVRAM:0xc00061f0d1 Grammar: StopWords:[user| assistant| system| <|im_end|> <|im_start|> <s> </s> <unk>] Cutstrings:[] TrimSpace:[] TrimSuffix:[] ContextSize:0xc00061f038 NUMA:false LoraAdapter: LoraBase: LoraScale:0 NoMulMatQ:false DraftModel: NDraft:0 Quantization: GPUMemoryUtilization:0 TrustRemoteCode:false EnforceEager:false SwapSpace:0 MaxModelLen:0 TensorParallelSize:0 MMProj: FlashAttention:false NoKVOffloading:false RopeScaling: ModelType: YarnExtFactor:0 YarnAttnFactor:0 YarnBetaFast:0 YarnBetaSlow:0} AutoGPTQ:{ModelBaseName: Device: Triton:false UseFastTokenizer:false} Diffusers:{CUDA:false PipelineType: SchedulerType: EnableParameters: CFGScale:0 IMG2IMG:false ClipSkip:0 ClipModel: ClipSubFolder: ControlNet:} Step:0 GRPC:{Attempts:0 AttemptsSleepTime:0} VallE:{AudioPath:} CUDA:false DownloadFiles:[] Description: Usage:}
api-1  | 4:09AM DBG templated message for chat: <|im_start|>user
api-1  | write a story about a castle siege<|im_end|>
api-1  | 
api-1  | 4:09AM DBG templated message for chat: <|im_start|>assistant
api-1  | Once upon a time, in a kingdom far away, there stood a majestic castle nestled on a hill overlooking the vast countryside. The castle was th<|im_end|>
api-1  | 
api-1  | 4:09AM DBG Prompt (before templating): <|im_start|>user
api-1  | write a story about a castle siege<|im_end|>
api-1  | 
api-1  | <|im_start|>assistant
api-1  | Once upon a time, in a kingdom far away, there stood a majestic castle nestled on a hill overlooking the vast countryside. The castle was th<|im_end|>
api-1  | 
api-1  | 4:09AM DBG Template found, input modified to: <|im_start|>user
api-1  | write a story about a castle siege<|im_end|>
api-1  | 
api-1  | <|im_start|>assistant
api-1  | Once upon a time, in a kingdom far away, there stood a majestic castle nestled on a hill overlooking the vast countryside. The castle was th<|im_end|>
api-1  | 
api-1  | <|im_start|>assistant
api-1  | 
api-1  | 4:09AM DBG Prompt (after templating): <|im_start|>user
api-1  | write a story about a castle siege<|im_end|>
api-1  | 
api-1  | <|im_start|>assistant
api-1  | Once upon a time, in a kingdom far away, there stood a majestic castle nestled on a hill overlooking the vast countryside. The castle was th<|im_end|>
api-1  | 
api-1  | <|im_start|>assistant
api-1  | 
api-1  | 4:09AM DBG Stream request received
api-1  | 4:09AM INF Success ip=172.19.0.1 latency="628.027µs" method=POST status=200 url=/v1/chat/completions
api-1  | 4:09AM DBG Sending chunk: {"created":1717906124,"object":"chat.completion.chunk","id":"8f381d3b-5916-402f-81f4-f64b8b496f6a","model":"Psyonic-Cetacean-Ultra-Quality-20b-Q8_0","choices":[{"index":0,"finish_reason":"","delta":{"role":"assistant","content":""}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
api-1  | 
api-1  | 4:09AM INF Loading model 'Psyonic-Cetacean-Ultra-Quality-20b-Q8_0.gguf' with backend llama
api-1  | 4:09AM DBG llama-cpp is an alias of llama-cpp
api-1  | 4:09AM DBG Model already loaded in memory: Psyonic-Cetacean-Ultra-Quality-20b-Q8_0.gguf`

**Additional context**
The issue appears to be present with preset models like `phi-3-mini-4k-instruct:fp16` too, and not limited to GPU. When cuda is turned off, the issue still exists.

**Comment by mudler** [comment]
Thanks for the heads up - this is already fixed by #2517 and will be available in the next release. Closing
