### ISSUE TITLE
Python Missing from AIO Images Downstream

### ISSUE THREAD

**Issue by lunamidori5** [mudler/LocalAI#2598]
**LocalAI version:**
All AIO 2.17

**Environment, CPU architecture, OS, and Version:**
Docker images

**Describe the bug**
Python and Pip are missing from the command line on 

**To Reproduce**
Run a docker buildx to install or run python programs

**Expected behavior**
python to work in non core images

**Logs**
```bash
#24 [21/26] RUN mv localai_entrypoint.sh /build/entrypoint_md_ai.sh
#24 CACHED
#25 [22/26] RUN pip install --no-cache-dir cryptography aiohttp tk
#25 0.514 /bin/bash: line 1: pip: command not found
#25 ERROR: process "/bin/bash -c pip install --no-cache-dir cryptography aiohttp tk" did not complete successfully: exit code: 127
------
 > [22/26] RUN pip install --no-cache-dir cryptography aiohttp tk:
0.514 /bin/bash: line 1: pip: command not found
------
localai-subsystem-dockerfile-cpu:32
--------------------
  30 |     RUN mv localai_entrypoint.sh /build/entrypoint_md_ai.sh
  31 |     
  32 | >>> RUN pip install --no-cache-dir cryptography aiohttp tk
  33 |     RUN python3 -m pip install --no-cache-dir -r midori_program_requirments.txt
  34 |     RUN python3 -m pip cache purge
--------------------
ERROR: failed to solve: process "/bin/bash -c pip install --no-cache-dir cryptography aiohttp tk" did not complete successfully: exit code: 127
Reference
Error: buildx failed with: ERROR: failed to solve: process "/bin/bash -c pip install --no-cache-dir cryptography aiohttp tk" did not complete successfully: exit code: 127
```

```bash
#25 [22/26] RUN python3 -m pip install --no-cache-dir cryptography aiohttp tk
#25 0.413 /bin/bash: line 1: python3: command not found
#25 ERROR: process "/bin/bash -c python3 -m pip install --no-cache-dir cryptography aiohttp tk" did not complete successfully: exit code: 127
------
 > [22/26] RUN python3 -m pip install --no-cache-dir cryptography aiohttp tk:
0.413 /bin/bash: line 1: python3: command not found
------
localai-subsystem-dockerfile-cpu:32
--------------------
  30 |     RUN mv localai_entrypoint.sh /build/entrypoint_md_ai.sh
  31 |     
  32 | >>> RUN python3 -m pip install --no-cache-dir cryptography aiohttp tk
  33 |     RUN python3 -m pip install --no-cache-dir -r midori_program_requirments.txt
  34 |     RUN python3 -m pip cache purge
--------------------
ERROR: failed to solve: process "/bin/bash -c python3 -m pip install --no-cache-dir cryptography aiohttp tk" did not complete successfully: exit code: 127
Reference
Error: buildx failed with: ERROR: failed to solve: process "/bin/bash -c python3 -m pip install --no-cache-dir cryptography aiohttp tk" did not complete successfully: exit code: 127
```

**Comment by mudler** [comment]
@lunamidori5 which images are you using?

**Comment by lunamidori5** [comment]
@mudler The CPU can not build due to no python, unable to test as it cant build in docker.

```
quay.io/go-skynet/local-ai:latest-aio-cpu
quay.io/go-skynet/local-ai:latest-aio-gpu-hipblas
quay.io/go-skynet/local-ai:latest-aio-gpu-intel-f32
quay.io/go-skynet/local-ai:latest-aio-gpu-intel-f16
quay.io/go-skynet/local-ai:latest-aio-gpu-nvidia-cuda-11
quay.io/go-skynet/local-ai:latest-aio-gpu-nvidia-cuda-12
```

Downstream dockerfiles

https://github.com/lunamidori5/Midori-AI/tree/master/other_files/subsystem_docker_stuff/localai

**Comment by maxvaneck** [comment]
i am currently running   the docker image latest-aio-cpu and  the logs are still complaining about mssing python . i'm getting the following line 
 

stderr /build/backend/python/diffusers/../common/libbackend.sh: line 97: /build/backend/python/diffusers/venv/bin/activate: No such file or directory
and

4:29PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:35223): stderr /build/backend/python/diffusers/../common/libbackend.sh: line 180: exec: python: not found

**Comment by marlemion** [comment]
I can also confirm that I was not able to find a docker image, which has python installed. Especially not latest.

Honestly, the whole core/extra idea is completely intransparent for outsiders. Even after understanding that there is a difference, it is still completely unclear whether images not having the core tag in the tag name actually include python or not.

Why python was a 'leftover' in the latest-cpu image while that image still offers models relying on python is also not clear.

**Comment by lunamidori5** [comment]
@marlemion and @maxvaneck I think they switched from python to uv, uv is easyer and faster way to manage python, can you check if your build files are right for the AIO dockerimage?
