### ISSUE TITLE
worker llama-cpp-rpc crash

### ISSUE THREAD

**Issue by JamesClarke7283** [mudler/LocalAI#2609]
**LocalAI version:**
[v2.17.1](https://github.com/mudler/LocalAI/releases/tag/v2.17.1)

**Environment, CPU architecture, OS, and Version:**
Linux desktop 6.9.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:37 +0000 x86_64 GNU/Linux
Archlinux

**Describe the bug**
The RPC worker crashes

**To Reproduce**
```bash
sudo wget https://github.com/mudler/LocalAI/releases/download/v2.17.1/local-ai-Linux-x86_64 -O /usr/bin/localai
sudo chmod +x /usr/bin/localai
/usr/bin/localai worker llama-cpp-rpc --debug -- 
```

**Expected behavior**
Runs without crash.

**Logs**
```
➜  ~ /usr/bin/localai worker llama-cpp-rpc --debug -- 

9:45AM DBG Setting logging to debug
9:45AM DBG Extracting backend assets files to /tmp/localai/backend_data
*** stack smashing detected ***: terminated
[1]    8658 IOT instruction (core dumped)  localai worker llama-cpp-rpc --debug --
➜  ~ 

```
**Additional context**

**Comment by mudler** [comment]
@JamesClarke7283 it's only the worker right? 

can you confirm if you start the normal HTTP server inference works?

**Comment by JamesClarke7283** [comment]
> @JamesClarke7283 it's only the worker right?
> 
> can you confirm if you start the normal HTTP server inference works?

yes, running localai normally works fine.

**Comment by JamesClarke7283** [comment]
Thanks, when will a release happen including this fix?
I prefer the binary builds rather than building myself.
