### ISSUE TITLE
404 on darwin/mac install.sh

### ISSUE THREAD

**Issue by BastLeblanc** [mudler/LocalAI#2644]
**LocalAI version:** 2.17

**Environment, CPU architecture, OS, and Version:**
Darwin 80a9971ecc6d 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030 arm64

**Describe the bug**
```
curl -L https://install.localai.io | sh

  Docker detected.
  Docker detected and no installation method specified. Using Docker.
  Downloading local-ai...
curl: (22) The requested URL returned error: 404
```
when ran with set -x
```
+ curl --fail --show-error --location --progress-bar -o /var/folders/st/dt42zf6x3tsf7zls21_75kch0000gq/T/tmp.yOHrpEeWUs/local-ai https://github.com/mudler/LocalAI/releases/download/vv2.17.1/local-ai-Darwin-
curl: (22) The requested URL returned error: 404
```
There's 2 errors, the double v in the version, and the arch is to recognised.

**To Reproduce**
curl -L https://install.localai.io | sh
on a mac

**Expected behavior**
is Mac ARM even supported?

**Comment by mudler** [comment]
@BastLeblanc hey, thanks for the issue - I do not have a mac to test this out and I did not managed to test the script on a Darwin system still.

We definetly support Mac, but is quite cumbersome to test it from here as I have to hijack GHA runners - out of curiosity - can you report what `uname -m` says on your system?

**Comment by mudler** [comment]
nevermind - figured out by having a closer look. Thanks for the report @BastLeblanc !
