### ISSUE TITLE
404 when running curl install.sh

### ISSUE THREAD

**Issue by syltensylten** [mudler/LocalAI#2650]
**Environment, CPU architecture, OS, and Version:**
x86_64, MacOS Monterey

**Describe the bug**
When trying to install LocalAI i get "curl: (22) The requested URL returned error: 404 ". 

I have updated curl and made sure its allowed internet. Also tried running with "sudo".  I tried pinging https://localai.io , unable to resolve host. However google.com works fine.

Cheers

**Comment by mudler** [comment]
We currently don't support x86_64 mac, but that's a good point - likely we can add back support to it (as we used to).

**Comment by syltensylten** [comment]
Thanks for your response. Hope to see support added again.

**Comment by syltensylten** [comment]
Thanks for your response. Hope to see support added again.
