### ISSUE TITLE
Intel Arc A770 LLM Fails

### ISSUE THREAD

**Issue by kprinssu** [mudler/LocalAI#3076]
I am trying to get text generation working on my Intel Arc A770 8GB and I am running into issues sycl not utilising the GPU. When I attempt to run use any prompt or any model I run into the following messages in the logs:

```
instance-1  | 9:55PM DBG GRPC(llava-v1.6-mistral-7b.Q5_K_M.gguf-127.0.0.1:34249): stderr Native API failed. Native API returns: -2 (PI_ERROR_DEVICE_NOT_AVAILABLE) -2 (PI_ERROR_DEVICE_NOT_AVAILABLE)
instance-1  | 9:55PM DBG GRPC(llava-v1.6-mistral-7b.Q5_K_M.gguf-127.0.0.1:34249): stderr Exception caught at file:/build/backend/cpp/llama-avx2/llama.cpp/ggml/src/ggml-sycl.cpp, line:3523, func:operator()
instance-1  | 9:55PM DBG GRPC(llava-v1.6-mistral-7b.Q5_K_M.gguf-127.0.0.1:34249): stderr SYCL error: CHECK_TRY_ERROR(dpct::gemm_batch( *main_stream, oneapi::mkl::transpose::trans, oneapi::mkl::transpose::nontrans, ne01, ne11, ne10, alpha, (const void **)(ptrs_src.get() + 0 * ne23), dpct::library_data_t::real_half, nb01 / nb00, (const void **)(ptrs_src.get() + 1 * ne23), dpct::library_data_t::real_half, nb11 / nb10, beta, (void **)(ptrs_dst.get() + 0 * ne23), cu_data_type, ne01, ne23, cu_compute_type)): Meet error in this line code!
instance-1  | 9:55PM DBG GRPC(llava-v1.6-mistral-7b.Q5_K_M.gguf-127.0.0.1:34249): stderr   in function ggml_sycl_mul_mat_batched_sycl at /build/backend/cpp/llama-avx2/llama.cpp/ggml/src/ggml-sycl.cpp:3523
instance-1  | 9:55PM DBG GRPC(llava-v1.6-mistral-7b.Q5_K_M.gguf-127.0.0.1:34249): stderr /build/backend/cpp/llama-avx2/llama.cpp/ggml/src/ggml-sycl/common.hpp:103: SYCL error
```

It looks like my hardware does not support half (f16) precision?

**LocalAI version:**

v2.19.3

**Environment, CPU architecture, OS, and Version:**

```
> uname -a
Linux kishor-docker 6.8.0-38-generic #38+TEST2072755v20240712b1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul 12 x86_64 x86_64 x86_64 GNU/Linux
```

Note: I had to use a custom test kernel from here: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2072755/comments/4 to fix my Intel Arc from timing out. It looks like the 6.8 kernel has regressions and I am now running into it.

Edit:

I tried the mainline 6.10.2 kernel and I am still running into the same error. I am still seeing GPU hangs and resets.

**Describe the bug**

**To Reproduce**

Attempt to use text generation via the Web UI with any LLM model.

**Expected behavior**

Text to be produced and llama.cpp not to crash.

**Logs**

Logs:
https://gist.github.com/kprinssu/6cc5e9798018e05098ec091d1b5f4611

Linux Kernel logs:
```
[26569.857186] i915 0000:01:00.0: [drm] GPU HANG: ecode 12:10:85def5fa, in grpcpp_sync_ser [352969]
[26569.857197] i915 0000:01:00.0: [drm] grpcpp_sync_ser[352969] context reset due to GPU hang
[26572.958874] Fence expiration time out i915-0000:01:00.0:grpcpp_sync_ser[352969]:54!
[26589.959895] Fence expiration time out i915-0000:01:00.0:grpcpp_sync_ser[352969]:56!
```

**Additional context**

Docker Compose:
```
services:
  instance:
    image: quay.io/go-skynet/local-ai:v2.19.3-aio-gpu-intel-f32
    privileged: true
    ports:
      - 8085:8080
    volumes:
      - ./models:/build/models
      - ./images:/tmp/generated/images/
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DEBUG=true
      - NEOReadDebugKeys=1
      - OverrideGpuAddressSpace=48
      - ZES_ENABLE_SYSMAN=1
    group_add:
      - 993
      - 996
      - 44

 ```
 
 Note: I need to to the extra env vars above as `sycl-ls` did not list my GPU due to the 6.8 kernel (https://github.com/intel/compute-runtime/issues/710 and https://github.com/intel/compute-runtime/issues/710#issuecomment-2002646557).

Example Model Config:

```
name: gpt4-gpu
mmap: false
context_size: 4096

f16: true
gpu_layers: 4

parameters:
  model: llava-v1.6-mistral-7b.Q5_K_M.gguf

stopwords:
- "<|im_end|>"
- "<dummy32000>"
- "</tool_call>"
- "<|eot_id|>"
- "<|end_of_text|>"
```

**Comment by mudler** [comment]
@kprinssu can you try disabling `f16` in the model configuration?

**Comment by kprinssu** [comment]
@mudler That works but llama.cpp does not use my GPU. It uses my CPU, pegs all of my CPU cores, and then does not stream nor produce any output (it does not stop).

**Comment by kprinssu** [comment]
I'll attempt to run a local build of llama and subsequently LocalAI on my host rather than via Docker and see if I run into the same error.

**Comment by kprinssu** [comment]
Just to follow up, it. indeed was a driver issue. I hacked in the Ubuntu 22.04 Jammy packages and it's working well. For reference, I had to use: https://chsasank.com/intel-arc-gpu-driver-oneapi-installation.html

**Comment by kprinssu** [comment]
Just for clarification, I was unable get LocalAI working with GPU acceleration and I have pivoted to running llama-cpp directly.

**Comment by KimSHenriksen** [comment]
You can try the vulkan version. You may have to manually update the yaml files for the models and specify gpu_layers. Start with a low number, if you set it too high you'll get an error like 'OutOfDeviceMemoryError'.

**Comment by mudler** [comment]
> Just for clarification, I was unable get LocalAI working with GPU acceleration and I have pivoted to running llama-cpp directly.

if you could share the logs I might help - otherwise it's hard. 

Did you tried the container images?

**Comment by kprinssu** [comment]
I have tried the images and unfortunately, I found that they stalled.I tried my own custom build of Ollama and it seems to be working very very well now.

@mudler  I believe these env vars will be helpful that I grabbed from [Intel's ipex-llm documentation](https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/ollama_quickstart.md). Would we be able to document these on the LocalAI docs? 

I found these helped accelerate the computation quite dramatically.

Environment variables:
```
ENV ZES_ENABLE_SYSMAN=1
ENV SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1
ENV SYCL_CACHE_PERSISTENT=1
ENV ONEAPI_DEVICE_SELECTOR=level_zero:0

# Only set this for Intel Arc and Intel Max GPUs
ENV USE_XETLA=OFF
```


I also found excellent documentation on what [each env var does on the sycl llvm repo.](https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md)
