### ISSUE TITLE
docker run --gpus all --name local-ai -ti localai/localai:latest-aio-gpu-nvidia-cuda-12 stuck forever

### ISSUE THREAD

**Issue by geverl** [mudler/LocalAI#3277]
**LocalAI version:**

**Environment, CPU architecture, OS, and Version:**

Intel i9, Ubuntu 22.04
**Describe the bug**

docker run --gpus all --name local-ai -ti localai/localai:latest-aio-gpu-nvidia-cuda-12
Unable to find image 'localai/localai:latest-aio-gpu-nvidia-cuda-12' locally
latest-aio-gpu-nvidia-cuda-12: Pulling from localai/localai
3713021b0277: Pull complete 
88ae6d3ddc27: Pull complete 
6f8d17fa39e3: Pull complete 
0e8d199ce128: Pull complete 
035735ff51ec: Pull complete 
bcce582b153a: Pull complete 
4f4fb700ef54: Pull complete 
d99219b95d7b: Pull complete 
79511ef28acd: Pull complete 
936a12ff35ee: Pull complete 
598c5aa97253: Pull complete 
b984306c80f7: Pull complete 
845a6453ac2c: Pull complete 
5c8a6ab2092c: Pull complete 
6e33a9cf7db6: Pull complete 
0e57cb2c4fd9: Pull complete 
130adcf65305: Pull complete 
f1386c42a1b2: Pull complete 
3326490c7246: Pull complete 
70c053988f65: Pull complete 
52f49a0c8d53: Pull complete 
6b6c6f38f957: Pull complete 
2f3de386b469: Pull complete 
a22daaf5784c: Extracting [==================================================>]  3.761GB/3.761GB
4d9d6159e34d: Downloading [=================================>                 ]  3.242GB/4.804GB
0b8e78cd5ba6: Downloading [=========================>                         ]   3.33GB/6.539GB
2fffcf20227a: Download complete 
fc7fe0b82ecd: Download complete 
0c618898a44c: Download complete

The docker run command stays stuck at this point and nothing happens.
**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

**Comment by NicolasGuilloux** [comment]
It happened to me once or twice while having an unstable internet connection. You may need to clean the layers and redownload it again.
I did a `docker image prune`, but keep in mind it will remove all unused images saved from your storage.

If it doesn't fix anything, then I guess it is something else ;) 
I downloaded the same image yesterday, it was slow but it was working.
