### ISSUE TITLE
image generation failure 

### ISSUE THREAD

**Issue by saket424** [mudler/LocalAI#3593]
**LocalAI version:** 

LocalAI version: v2.20.1 AIO-GPU-cuda12

**Environment, CPU architecture, OS, and Version:**

Linux dell4090 6.9.3-76060903-generic #202405300957~1721174657~22.04~abb7c06 SMP PREEMPT_DYNAMIC Wed J x86_64 x86_64 x86_64 GNU/Linux

anand@dell4090:~/baibot$ nvidia-smi
Tue Sep 17 15:01:42 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:01:00.0 Off |                  Off |
|  0%   34C    P8             12W /  450W |    7390MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1261      G   /usr/lib/xorg/Xorg                              9MiB |
|    0   N/A  N/A      4126      G   /usr/bin/gnome-shell                           10MiB |
|    0   N/A  N/A      9724      C   .../backend-assets/grpc/llama-cpp-avx2       6448MiB |
|    0   N/A  N/A     13565      C   ...nd_data/backend-assets/grpc/whisper        892MiB |
+-----------------------------------------------------------------------------------------+
**Describe the bug**

image generation results in a 500 error. is it because of insufficient space?

**To Reproduce**

curl http://172.17.0.1:8080/v1/images/generations \
  -H "Content-Type: application/json" \
  -d '{
    "model": "stablediffusion",
    "prompt": "a beautiful sunset over the ocean",
    "step": 25,
    "size": "512x512"
  }'
{"error":{"code":500,"message":"could not load model (no success): Unexpected err=RepositoryNotFoundError('401 Client Error. (Request ID: Root=1-66e9e009-4132d8e7085844513301a355;6b4bf3ff-f34a-4cbc-8e5e-0d9a3cf498d6)\\n\\nRepository Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/revision/main.\\nPlease make sure you specified the correct `repo_id` and `repo_type`.\\nIf you are trying to access a private or gated repo, make sure you are authenticated.\\nInvalid username or password.'), type(err)=\u003cclass 'huggingface_hub.utils._errors.RepositoryNotFoundError'\u003e","type":""}}

**Expected behavior**

**Logs**

7:42PM INF Success ip=127.0.0.1 latency="30.447µs" method=GET status=200 url=/readyz
7:43PM DBG Request received: {"model":"stablediffusion","language":"","translate":false,"n":1,"top_p":null,"top_k":null,"temperature":null,"max_tokens":null,"echo":false,"batch":0,"ignore_eos":false,"repeat_penalty":0,"repeat_last_n":0,"n_keep":0,"frequency_penalty":0,"presence_penalty":0,"tfz":null,"typical_p":null,"seed":null,"negative_prompt":"","rope_freq_base":0,"rope_freq_scale":0,"negative_prompt_scale":0,"use_fast_tokenizer":false,"clip_skip":0,"tokenizer":"","file":"","response_format":"b64_json","size":"256x256","prompt":"a beautiful sunset over the ocean","instruction":"","input":null,"stop":null,"messages":null,"functions":null,"function_call":null,"stream":false,"mode":0,"step":0,"grammar":"","grammar_json_functions":null,"backend":"","model_base_name":""}
7:43PM DBG Loading model: stablediffusion
7:43PM DBG guessDefaultsFromFile: not a GGUF file
7:43PM DBG Parameter Config: &{PredictionOptions:{Model:DreamShaper_8_pruned.safetensors Language: Translate:false N:0 TopP:0xc001007728 TopK:0xc001007730 Temperature:0xc001007738 Maxtokens:0xc001007768 Echo:false Batch:0 IgnoreEOS:false RepeatPenalty:0 RepeatLastN:0 Keep:0 FrequencyPenalty:0 PresencePenalty:0 TFZ:0xc001007760 TypicalP:0xc001007758 Seed:0xc001007780 NegativePrompt: RopeFreqBase:0 RopeFreqScale:0 NegativePromptScale:0 UseFastTokenizer:false ClipSkip:0 Tokenizer:} Name:stablediffusion F16:0xc0010076a5 Threads:0xc001007718 Debug:0xc0015121b0 Roles:map[] Embeddings:0xc001007779 Backend:diffusers TemplateConfig:{Chat: ChatMessage: Completion: Edit: Functions: UseTokenizerTemplate:false JoinChatMessagesByCharacter:<nil>} PromptStrings:[a beautiful sunset over the ocean] InputStrings:[] InputToken:[] functionCallString: functionCallNameString: ResponseFormat:b64_json ResponseFormatMap:map[] FunctionsConfig:{DisableNoAction:false GrammarConfig:{ParallelCalls:false DisableParallelNewLines:false MixedMode:false NoMixedFreeString:false NoGrammar:false Prefix: ExpectStringsAfterJSON:false PropOrder: SchemaType:} NoActionFunctionName: NoActionDescriptionName: ResponseRegex:[] JSONRegexMatch:[] ReplaceFunctionResults:[] ReplaceLLMResult:[] CaptureLLMResult:[] FunctionNameKey: FunctionArgumentsKey:} FeatureFlag:map[] LLMConfig:{SystemPrompt: TensorSplit: MainGPU: RMSNormEps:0 NGQA:0 PromptCachePath: PromptCacheAll:false PromptCacheRO:false MirostatETA:0xc001007750 MirostatTAU:0xc001007748 Mirostat:0xc001007740 NGPULayers:0xc001007770 MMap:0xc001007778 MMlock:0xc001007779 LowVRAM:0xc001007779 Grammar: StopWords:[] Cutstrings:[] TrimSpace:[] TrimSuffix:[] ContextSize:0xc001007710 NUMA:false LoraAdapter: LoraBase: LoraScale:0 NoMulMatQ:false DraftModel: NDraft:0 Quantization: GPUMemoryUtilization:0 TrustRemoteCode:false EnforceEager:false SwapSpace:0 MaxModelLen:0 TensorParallelSize:0 MMProj: FlashAttention:false NoKVOffloading:false RopeScaling: ModelType: YarnExtFactor:0 YarnAttnFactor:0 YarnBetaFast:0 YarnBetaSlow:0} AutoGPTQ:{ModelBaseName: Device: Triton:false UseFastTokenizer:false} Diffusers:{CUDA:true PipelineType:StableDiffusionPipeline SchedulerType:k_dpmpp_2m EnableParameters:negative_prompt,num_inference_steps CFGScale:0 IMG2IMG:false ClipSkip:0 ClipModel: ClipSubFolder: ControlNet:} Step:25 GRPC:{Attempts:0 AttemptsSleepTime:0} TTSConfig:{Voice: VallE:{AudioPath:}} CUDA:false DownloadFiles:[{Filename:DreamShaper_8_pruned.safetensors SHA256: URI:huggingface://Lykon/DreamShaper/DreamShaper_8_pruned.safetensors}] Description: Usage:curl http://localhost:8080/v1/images/generations \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "<positive prompt>|<negative prompt>",
    "step": 25,
    "size": "512x512"
  }'}
7:43PM INF Loading model 'DreamShaper_8_pruned.safetensors' with backend diffusers
7:43PM DBG Loading model in memory from file: /build/models/DreamShaper_8_pruned.safetensors
7:43PM DBG Loading Model DreamShaper_8_pruned.safetensors with gRPC (file: /build/models/DreamShaper_8_pruned.safetensors) (backend: diffusers): {backendString:diffusers model:DreamShaper_8_pruned.safetensors threads:16 assetDir:/tmp/localai/backend_data context:{emptyCtx:{}} gRPCOptions:0xc000bb0488 externalBackends:map[autogptq:/build/backend/python/autogptq/run.sh bark:/build/backend/python/bark/run.sh coqui:/build/backend/python/coqui/run.sh diffusers:/build/backend/python/diffusers/run.sh exllama:/build/backend/python/exllama/run.sh exllama2:/build/backend/python/exllama2/run.sh huggingface-embeddings:/build/backend/python/sentencetransformers/run.sh mamba:/build/backend/python/mamba/run.sh openvoice:/build/backend/python/openvoice/run.sh parler-tts:/build/backend/python/parler-tts/run.sh rerankers:/build/backend/python/rerankers/run.sh sentencetransformers:/build/backend/python/sentencetransformers/run.sh transformers:/build/backend/python/transformers/run.sh transformers-musicgen:/build/backend/python/transformers-musicgen/run.sh vall-e-x:/build/backend/python/vall-e-x/run.sh vllm:/build/backend/python/vllm/run.sh] grpcAttempts:20 grpcAttemptsDelay:2 singleActiveBackend:false parallelRequests:false}
7:43PM DBG Loading external backend: /build/backend/python/diffusers/run.sh
7:43PM DBG Loading GRPC Process: /build/backend/python/diffusers/run.sh
7:43PM DBG GRPC Service for DreamShaper_8_pruned.safetensors will be running at: '127.0.0.1:43255'
7:43PM DBG GRPC Service state dir: /tmp/go-processmanager2870825797
7:43PM DBG GRPC Service Started
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stdout Initializing libbackend for build
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stdout virtualenv activated
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stdout activated virtualenv has been ensured
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr /build/backend/python/diffusers/venv/lib/python3.10/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr   warnings.warn(
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr There was a problem when trying to move your cache:
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr 
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr   File "/build/backend/python/diffusers/venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 1325, in <module>
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr     move_cache()
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr 
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr   File "/build/backend/python/diffusers/venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 1234, in move_cache
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr     cached_files = get_all_cached_files(cache_dir=cache_dir)
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr 
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr   File "/build/backend/python/diffusers/venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 1133, in get_all_cached_files
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr     url = metadata["url"]
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr 
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr KeyError: 'url'
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr 
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr Please file an issue at https://github.com/huggingface/transformers/issues/new/choose and copy paste this whole message and we will do our best to help.
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr Server started. Listening on: 127.0.0.1:43255
7:43PM DBG GRPC Service Ready
7:43PM DBG GRPC: Loading model with options: {state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:<nil>} sizeCache:0 unknownFields:[] Model:DreamShaper_8_pruned.safetensors ContextSize:512 Seed:1932242786 NBatch:512 F16Memory:true MLock:false MMap:true VocabOnly:false LowVRAM:false Embeddings:false NUMA:false NGPULayers:99999999 MainGPU: TensorSplit: Threads:16 LibrarySearchPath: RopeFreqBase:0 RopeFreqScale:0 RMSNormEps:0 NGQA:0 ModelFile:/build/models/DreamShaper_8_pruned.safetensors Device: UseTriton:false ModelBaseName: UseFastTokenizer:false PipelineType:StableDiffusionPipeline SchedulerType:k_dpmpp_2m CUDA:true CFGScale:0 IMG2IMG:false CLIPModel: CLIPSubfolder: CLIPSkip:0 ControlNet: Tokenizer: LoraBase: LoraAdapter: LoraScale:0 NoMulMatQ:false DraftModel: AudioPath: Quantization: GPUMemoryUtilization:0 TrustRemoteCode:false EnforceEager:false SwapSpace:0 MaxModelLen:0 TensorParallelSize:0 MMProj: RopeScaling: YarnExtFactor:0 YarnAttnFactor:0 YarnBetaFast:0 YarnBetaSlow:0 Type: FlashAttention:false NoKVOffload:false}
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr Loading model DreamShaper_8_pruned.safetensors...
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr Request Model: "DreamShaper_8_pruned.safetensors"
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr ContextSize: 512
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr Seed: 1932242786
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr NBatch: 512
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr F16Memory: true
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr MMap: true
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr NGPULayers: 99999999
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr Threads: 16
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr ModelFile: "/build/models/DreamShaper_8_pruned.safetensors"
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr PipelineType: "StableDiffusionPipeline"
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr SchedulerType: "k_dpmpp_2m"
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr CUDA: true
7:43PM DBG GRPC(DreamShaper_8_pruned.safetensors-127.0.0.1:43255): stderr 
7:43PM ERR Server error error="could not load model (no success): Unexpected err=RepositoryNotFoundError('401 Client Error. (Request ID: Root=1-66e9dbdd-48e8a13d7189d98a5b5c18d9;cf628ac4-ff72-477b-a3ca-4868f3bb6a12)\\n\\nRepository Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/revision/main.\\nPlease make sure you specified the correct `repo_id` and `repo_type`.\\nIf you are trying to access a private or gated repo, make sure you are authenticated.\\nInvalid username or password.'), type(err)=<class 'huggingface_hub.utils._errors.RepositoryNotFoundError'>" ip=172.18.0.1 latency=6.261046189s method=POST status=500 url=/v1/images/generations
7:43PM INF Success ip=127.0.0.1 latency="29.816µs" method=GET status=200 url=/readyz

**Additional context**

Can you give me a clue on what the issue is and why i am seeing a 401 and 500 error

**Comment by jakommo** [comment]
The problem is that it's trying to access the runwayml huggingface repo, which is not available anymore. See discussion here with a dirty workaround https://github.com/mudler/LocalAI/discussions/3496

**Comment by saket424** [comment]
@jakommo 
Thanks for the dirty workaround. That fixed it
