### ISSUE TITLE
gpt-4-vision-preview is no longer a valid model. Replace with gpt-4o instead 

### ISSUE THREAD

**Issue by saket424** [mudler/LocalAI#3596]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

For completeness, it should be noted that for the actual OpenAI API (recommended to be used via the openai provider), gpt-4-vision-preview is no longer a valid model.

If you try to use it, you get an error:

invalid_request_error: The model gpt-4-vision-preview has been deprecated, learn more here: https://platform.openai.com/docs/deprecations (code: model_not_found)

Here's the relevant part:

On June 6th, 2024, we notified developers using gpt-4-32k and gpt-4-vision-preview of their upcoming deprecations in one year and six months respectively. As of June 17, 2024, only existing users of these models will be able to continue using them.

Using gpt-4o is the new equivalent to using gpt-4-vision-preview.

**Describe alternatives you've considered**

**Additional context**

References to gpt-4-vision-preview in https://github.com/mudler/LocalAI/blob/master/aio/gpu-8g/vision.yaml and

https://github.com/mudler/LocalAI/blob/master/aio/cpu/vision.yaml and

https://github.com/mudler/LocalAI/blob/master/aio/intel/vision.yaml

need to be changed to gpt-4o in the next docker aio pre-packaged templates

Thanks

**Comment by mudler** [comment]
good point - this is something we should look at
