### ISSUE TITLE
[bug] docker image show can't find llama backend

### ISSUE THREAD

**Issue by Hisir0909** [mudler/LocalAI#3673]
**LocalAI version:**

v2.21.0-cublas-cuda12-ffmpeg-core(❌), v2.21.1-cublas-cuda12-core(❌), v2.19.4-cublas-cuda12-ffmpeg-core(✅)
**Environment, CPU architecture, OS, and Version:**

Ubuntu 24.04 LTS (GNU/Linux 6.8.0-45-generic x86_64)

![image](https://github.com/user-attachments/assets/31485db0-364a-4fb3-b2f7-2bf902fb2dfa)
![image](https://github.com/user-attachments/assets/93a84606-64bb-47f8-9920-48644acaf11a)

**Describe the bug**

![image](https://github.com/user-attachments/assets/b75429dd-0e3b-4986-80e2-a3680d8cad8a)

When I use the latest two versions of the image, it prompts that the llama backend cannot be found, but it was normal in the previous versions.

**To Reproduce**

Pull the new image and then up. An error was found during the request; the model's YAML configuration specifies the backend as llama.

**Expected behavior**
Like normal reasoning in version 2.19.

**Logs**
no other

**Additional context**
If there is any other information needed, please let me know.

**Comment by github0null** [comment]
Same here, but i found a temporary solution:

`docker exec -it <your container id> /bin/bash`

```shell
cp /tmp/localai/backend_data/backend-assets/grpc/llama-cpp-grpc /tmp/localai/backend_data/backend-assets/grpc/llama-cpp
```

**Comment by TheDarkTrumpet** [comment]
You can also change your YAML files to just do the following:

```
backend: llama-cpp-grpc
```

**Comment by mudler** [comment]
good catch, this should be fixed by https://github.com/mudler/LocalAI/pull/3789
