### ISSUE TITLE
Proposal: Move `examples` to their own repo

### ISSUE THREAD

**Issue by dave-gray101** [mudler/LocalAI#4010]
_Part of the CI Speedup Project https://github.com/users/dave-gray101/projects/2/views/1_

I propose that we create a new repo `localai-examples` and migrate all existing and future examples to that repo.

Currently, we do not actually run automated tests on any of our examples. This does not seem likely to change at any time soon, as we've got plenty on our plates to work on. 

Dependabot is automatically generating PRs and running CI for each individual example. Regardless of if we think it's wise to automatically update the dependencies in those mini-projects without testing or not, I believe it makes the most sense to move them to their own repo, with their own testing, update, and CI policies.

I'm happy to create this myself, or wait for you to create a @mudler / localai-examples.

At the same time that the examples are migrated, I propose we change them to reference released versions of LocalAI rather than master - this is mostly going to be a technical change, but I want to document it here since I think that it's actually better to show that to our users anyway.

**Comment by mudler** [comment]
Yes :100: ! Examples are really a pain for the CI currently, and makes totally sense have a separate repository. I've created https://github.com/mudler/LocalAI-examples to move the current examples out but we can have also multiple repositories. The only problem I see is keeping these functional, as versions could have been bumped invalidating some of the examples code.

**Comment by dave-gray101** [comment]
https://github.com/mudler/LocalAI-examples has been updated:

- Now has all the content from the main repo
- Has a disclaimer on the top that things may be out of date

https://github.com/mudler/LocalAI/pull/4017 was created to drop them from LocalAI itself. Closing this issue as the proposal itself is pretty settled at this time.
