### ISSUE TITLE
p2p inferencing not work

### ISSUE THREAD

**Issue by mintyleaf** [mudler/LocalAI#4214]
**LocalAI version:**
7adbc16 (7adbc16bae68d3e784096d156145d861e2edec8b)

**Environment, CPU architecture, OS, and Version:**
some vast.ai nvidia gpu instance

**Describe the bug**
![telegram-cloud-photo-size-2-5327815199232747918-y](https://github.com/user-attachments/assets/3a949e37-5c0d-43b9-9403-ad6d4c4b4a56)

**To Reproduce**
just try to start p2p worker node in the working p2p environment  

**Additional context**
using latest master docker image with my p2p fixes makes everything work in federated mode and connect two nodes with third just head server cpu node (+ using own DHT for faster discovery), yet, that only works for federated mode, worker is stuck in the loop here: https://github.com/mudler/LocalAI/blob/eaf0e3022a131820d2c73d1daa9aa7282d2b5d81/core/cli/worker/worker_p2p.go#L70-L76

i'll try to investigate that further, but maybe you can get the idea of what is happening faster

**Comment by mudler** [comment]
Seems there was a regression: should be fixed by https://github.com/mudler/LocalAI/pull/4220

**Comment by pratikbin** [comment]
https://github.com/mudler/LocalAI/issues/3968
