### ISSUE TITLE
Downloads Models At Start No Matter what you do

### ISSUE THREAD

**Issue by levidehaan** [mudler/LocalAI#4217]
We dont want to download a bunch of useless models we dont need, why do all the docker images download models at the beginning? its breaking everything!

**Comment by mudler** [comment]
@levidehaan only the AIO images brings pre-loaded models. See the getting started: https://localai.io/basics/getting_started/#running-localai-with-all-in-one-aio-images and https://localai.io/basics/container/ for all the available options.

**Comment by meonkeys** [comment]
also see #8277 -- the aio image was doing this for me too but the non-aio image works as I expect (doesn't try to download stuff I already have).
