### ISSUE TITLE
After updating to 2.24 LLM hangs after first response

### ISSUE THREAD

**Issue by rabner** [mudler/LocalAI#4334]
**LocalAI version:**

localai/localai:latest-aio-gpu-nvidia-cuda-12 (v2.24.0)

**Environment, CPU architecture, OS, and Version:**

Proxmox 8.3.1; Docker in unprivileged LXC; RTX 3090 driver: 565.57.01; Xeon E5v4; /models directory is persistent 

**Describe the bug**

After updating to 2.24 LLM hangs after first response, nothing works. Container restart restores it, but only for one prompt...
Tested on LocaAI chat UI, OpenWebUI, various models.
Embedding models seems to work from curl.

**To Reproduce**

**Expected behavior**

**Logs**

[localai.log](https://github.com/user-attachments/files/18048145/localai.log)

**Additional context**

When all started I've updated GPU drivers and systems to latest versions, rebooted proxmox few times etc.
I have Ollama in the same setup and it still works, so I don't think it is hardware/system related.

**Comment by rabner** [comment]
Workaround by reverting to 2.23.

**Comment by superjamie** [comment]
Same result here. Running the same models in plain llama.cpp container and LM Studio AppImage work fine.

**LocalAI version:**

quay.io/go-skynet/local-ai:latest-vulkan-ffmpeg-core

**Environment, CPU architecture, OS, and Version:**

Intel Alder Lake CPU, AMD RX 5600 XT GPU (no ROCm), Debian 12, rootless Podman

**Comment by mudler** [comment]
Thanks for raising this up, confirmed and patch release is on its way already :+1:

**Comment by mudler** [comment]
this should be fixed in 2.24.1

**Comment by superjamie** [comment]
All good now. Thank you very much!
