### ISSUE TITLE
llama-cpp generates CUDA error - an illegal memory access was encountered 

### ISSUE THREAD

**Issue by Francisco-Macha** [mudler/LocalAI#4354]
**LocalAI version:**
LocalAI 2.24.1

**Environment, CPU architecture, OS, and Version:**
Linux gpu01 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
Unable to load model hermes-3-llama-3.1-8b into GPU - generates "CUDA error: an illegal memory access was encountered" 
Model is upstream from Model Gallery - changed to 128k context size
GPU is H100

**To Reproduce**
Fresh build of 2.24.1 (docker build)
Send inferences request to this model 

**Expected behavior**
Should generate text from prompt - has been working with v2.22 and v2.23 

**Logs**
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: format           = GGUF V3 (latest)
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: arch             = llama
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: vocab type       = BPE
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_vocab          = 128256
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_merges         = 280147
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: vocab_only       = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_ctx_train      = 131072
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_embd           = 4096
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_layer          = 32
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_head           = 32
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_head_kv        = 8
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_rot            = 128
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_swa            = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_embd_head_k    = 128
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_embd_head_v    = 128
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_gqa            = 4
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_embd_k_gqa     = 1024
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_embd_v_gqa     = 1024
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: f_norm_eps       = 0.0e+00
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: f_clamp_kqv      = 0.0e+00
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: f_max_alibi_bias = 0.0e+00
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: f_logit_scale    = 0.0e+00
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_ff             = 14336
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_expert         = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_expert_used    = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: causal attn      = 1
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: pooling type     = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: rope type        = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: rope scaling     = linear
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: freq_base_train  = 500000.0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: freq_scale_train = 1
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: n_ctx_orig_yarn  = 131072
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: rope_finetuned   = unknown
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: ssm_d_conv       = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: ssm_d_inner      = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: ssm_d_state      = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: ssm_dt_rank      = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: ssm_dt_b_c_rms   = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: model type       = 8B
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: model ftype      = Q8_0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: model params     = 8.03 B
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: model size       = 7.95 GiB (8.50 BPW)
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: general.name     = Hermes 3 Llama 3.1 8B
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: EOS token        = 128040 '<|im_end|>'
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: EOT token        = 128040 '<|im_end|>'
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: EOM token        = 128008 '<|eom_id|>'
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: PAD token        = 128040 '<|im_end|>'
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: LF token         = 128 'Ä'
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: EOG token        = 128008 '<|eom_id|>'
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: EOG token        = 128009 '<|eot_id|>'
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: EOG token        = 128040 '<|im_end|>'
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_print_meta: max token length = 256
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_tensors: tensor 'token_embd.weight' (q8_0) (and 0 others) cannot be used with preferred buffer type CPU_AARCH64, using CPU instead
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_tensors: offloading 32 repeating layers to GPU
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_tensors: offloading output layer to GPU
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_tensors: offloaded 33/33 layers to GPU
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_tensors:   CPU_Mapped model buffer size =   532.31 MiB
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llm_load_tensors:        CUDA0 model buffer size =  7605.33 MiB
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr .........................................................................................
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model: n_seq_max     = 1
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model: n_ctx         = 131072
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model: n_ctx_per_seq = 131072
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model: n_batch       = 512
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model: n_ubatch      = 512
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model: flash_attn    = 0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model: freq_base     = 500000.0
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model: freq_scale    = 1
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_kv_cache_init:      CUDA0 KV buffer size = 16384.00 MiB
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model: KV self size  = 16384.00 MiB, K (f16): 8192.00 MiB, V (f16): 8192.00 MiB
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model:  CUDA_Host  output buffer size =     0.49 MiB
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model:      CUDA0 compute buffer size =  8480.00 MiB
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model:  CUDA_Host compute buffer size =   264.01 MiB
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model: graph nodes  = 1030
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr llama_new_context_with_model: graph splits = 2
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
2:32AM DBG [WatchDog] Watchdog checks for busy connections
2:32AM DBG [WatchDog] 127.0.0.1:43767: active connection
2:32AM DBG [WatchDog] Watchdog checks for idle connections
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stdout {"timestamp":1733797947,"level":"INFO","function":"initialize","line":547,"message":"initializing slots","n_slots":1}
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stdout {"timestamp":1733797947,"level":"INFO","function":"initialize","line":556,"message":"new slot","slot_id":0,"n_ctx_slot":131072}
2:32AM INF [llama-cpp] Loads OK
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stdout {"timestamp":1733797947,"level":"INFO","function":"launch_slot_with_data","line":928,"message":"slot is processing task","slot_id":0,"task_id":0}
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stdout {"timestamp":1733797947,"level":"INFO","function":"update_slots","line":1825,"message":"kv cache rm [p0, end)","slot_id":0,"task_id":0,"p0":0}
**2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr CUDA error: an illegal memory access was encountered
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr   current device: 0, in function ggml_backend_cuda_synchronize at /build/backend/cpp/llama-fallback/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2282
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr   cudaStreamSynchronize(cuda_ctx->stream())
2:32AM DBG GRPC(hermes-3-llama-3.1-8b_128k-127.0.0.1:43767): stderr /build/backend/cpp/llama-fallback/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:70: CUDA error**
2:32AM INF Success ip=127.0.0.1 latency="109.656µs" method=GET status=200 url=/readyz

**Additional context**
This seems to be backend issue to llama-cpp -
https://github.com/ggerganov/llama.cpp/issues/10739 - Eval bug: llama-server: illegal memory access was encountered

**Comment by mudler** [comment]
good catch, this candidates for a 2.24.2 patch release :+1:

**Comment by Francisco-Macha** [comment]
Awesome! Thank you for the quick turnaround!! 

Not sure if this is related (or another net-new bug issue?) - am rebuilding locally (docker build...) and now am encountering this error:

```
 => CACHED [stage-9 10/13] RUN if [[ ( "${EXTRA_BACKENDS}" =~ "coqui" || -z "${EXTRA_BACKENDS  0.0s
=> ERROR [stage-9 11/13] RUN if [[ ( "${EXTRA_BACKENDS}" =~ "vall-e-x" || -z "${EXTRA_BACKE  21.6s
------
.
.
.
15.47 make: Leaving directory '/build/backend/python/vall-e-x'
15.47 make: Entering directory '/build/backend/python/openvoice'
15.47 python3 -m grpc_tools.protoc -I../.. --python_out=. --grpc_python_out=. backend.proto
15.51 bash install.sh
15.52 Initializing libbackend for openvoice
15.53 Using CPython 3.10.12 interpreter at: /usr/bin/python
15.53 Creating virtual environment at: venv
15.53 virtualenv created
15.53 virtualenv activated
15.53 activated virtualenv has been ensured
15.53 starting requirements install for /build/backend/python/openvoice/requirements.txt
15.57 Using Python 3.10.12 environment at venv
16.11 Resolved 125 packages in 535ms
18.04 Prepared 24 packages in 1.91s
18.69 Installed 125 packages in 655ms
18.69  + aiofiles==23.2.1
18.69  + altair==5.5.0
18.69  + annotated-types==0.7.0
18.69  + anyio==4.7.0
18.69  + attrs==24.2.0
18.69  + audioread==3.0.1
18.69  + av==14.0.1
18.69  + certifi==2024.8.30
18.69  + cffi==1.17.1
18.69  + charset-normalizer==3.4.0
18.69  + click==8.1.7
18.69  + cn2an==0.5.22
18.69  + coloredlogs==15.0.1
18.69  + contourpy==1.2.1
18.69  + ctranslate2==4.5.0
18.69  + cycler==0.12.1
18.69  + cython==3.0.11
18.69  + decorator==5.1.1
18.69  + distro==1.9.0
18.69  + dtw-python==1.4.4
18.69  + eng-to-ipa==0.0.2
18.69  + exceptiongroup==1.2.2
18.69  + fastapi==0.115.6
18.69  + faster-whisper==1.1.0
18.69  + ffmpy==0.4.0
18.69  + filelock==3.16.1
18.69  + flatbuffers==24.3.25
18.69  + fonttools==4.55.3
18.69  + fsspec==2024.10.0
18.69  + gradio==3.48.0
18.69  + gradio-client==0.6.1
18.69  + grpcio==1.68.1
18.69  + h11==0.14.0
18.69  + httpcore==1.0.7
18.69  + httpx==0.28.1
18.69  + huggingface-hub==0.26.5
18.69  + humanfriendly==10.0
18.69  + idna==3.10
18.69  + importlib-resources==6.4.5
18.69  + inflect==7.4.0
18.69  + jieba==0.42.1
18.69  + jinja2==3.1.4
18.69  + jiter==0.8.2
18.69  + joblib==1.4.2
18.69  + jsonschema==4.23.0
18.69  + jsonschema-specifications==2024.10.1
18.69  + kiwisolver==1.4.7
18.69  + langid==1.1.6
18.69  + lazy-loader==0.4
18.69  + librosa==0.10.0
18.69  + llvmlite==0.43.0
18.69  + markupsafe==2.1.5
18.69  + matplotlib==3.8.4
18.69  + more-itertools==10.5.0
18.69  + mpmath==1.3.0
18.69  + msgpack==1.1.0
18.69  + narwhals==1.17.0
18.69  + networkx==2.8.8
18.69  + numba==0.60.0
18.69  + numpy==1.22.0
18.69  + nvidia-cublas-cu12==12.4.5.8
18.69  + nvidia-cuda-cupti-cu12==12.4.127
18.69  + nvidia-cuda-nvrtc-cu12==12.4.127
18.69  + nvidia-cuda-runtime-cu12==12.4.127
18.69  + nvidia-cudnn-cu12==9.1.0.70
18.69  + nvidia-cufft-cu12==11.2.1.3
18.69  + nvidia-curand-cu12==10.3.5.147
18.69  + nvidia-cusolver-cu12==11.6.1.9
18.69  + nvidia-cusparse-cu12==12.3.1.170
18.69  + nvidia-nccl-cu12==2.21.5
18.69  + nvidia-nvjitlink-cu12==12.4.127
18.69  + nvidia-nvtx-cu12==12.4.127
18.69  + onnxruntime==1.20.1
18.69  + openai==1.57.2
18.69  + openai-whisper==20240930
18.69  + orjson==3.10.12
18.69  + packaging==24.2
18.69  + pandas==2.0.3
18.69  + pillow==10.4.0
18.69  + platformdirs==4.3.6
18.69  + pooch==1.8.2
18.69  + proces==0.1.7
18.69  + protobuf==5.29.1
18.69  + pycparser==2.22
18.69  + pydantic==2.10.3
18.69  + pydantic-core==2.27.1
18.69  + pydub==0.25.1
18.69  + pyparsing==3.2.0
18.69  + pypinyin==0.53.0
18.69  + python-dateutil==2.9.0.post0
18.69  + python-dotenv==1.0.1
18.69  + python-multipart==0.0.19
18.69  + pytz==2024.2
18.69  + pyyaml==6.0.2
18.69  + referencing==0.35.1
18.69  + regex==2024.11.6
18.69  + requests==2.32.3
18.69  + resampy==0.4.3
18.69  + rpds-py==0.22.3
18.69  + scikit-learn==1.6.0
18.69  + scipy==1.11.4
18.69  + semantic-version==2.10.0
18.69  + setuptools==75.6.0
18.69  + six==1.17.0
18.69  + sniffio==1.3.1
18.69  + soundfile==0.12.1
18.69  + soxr==0.5.0.post1
18.69  + starlette==0.41.3
18.69  + sympy==1.13.1
18.69  + threadpoolctl==3.5.0
18.69  + tiktoken==0.8.0
18.69  + tokenizers==0.21.0
18.69  + torch==2.5.1
18.69  + torchaudio==2.5.1
18.69  + tqdm==4.67.1
18.69  + triton==3.1.0
18.69  + typeguard==4.4.1
18.69  + typing-extensions==4.12.2
18.69  + tzdata==2024.2
18.69  + unidecode==1.3.8
18.69  + urllib3==2.2.3
18.69  + uvicorn==0.32.1
18.69  + wavmark==0.0.3
18.69  + websockets==11.0.3
18.69  + whisper-timestamped==1.15.8
18.72 finished requirements install for /build/backend/python/openvoice/requirements.txt
18.74 /build/backend/python/openvoice/venv/bin/python: No module named unidic
18.74 make: *** [Makefile:5: install] Error 1
18.74 make: Leaving directory '/build/backend/python/openvoice'
------
Dockerfile:451
.
.
```


From what I can gather, this coming  from the  backend/python/openvoice/install.sh   exec (invoked via make install  for this backend through docker build)

Am comparing the backend/python/openvoice tree in branches 2.23,  2.24 and 2.24.1  and all seem to be ok. 

Will attempt to further debug/troubleshoot - may end up skipping this backend if not able to figure this out. 
What's puzzling is the docker build should prevent deviations from how the package is built locally....   keep you posted!

**Comment by mudler** [comment]
thanks @Francisco-Macha - it looks indeed another issue so please create another bug, however Docker builds in the CI succeeded, so maybe it's some volatile error on your end? 

Closing this issue as it is solved now

**Comment by Francisco-Macha** [comment]
quick one - issued a net-new git clone of the 2.24.2 branch , docker build worked - models load on the H100.

Thanks again!!
