### ISSUE TITLE
feat: Add swagger docs

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#57]
https://github.com/go-skynet/LocalAI/pull/168 ( https://github.com/gofiber/swagger )

**Comment by chris-spencer** [comment]
I'd love this. But could we consider having a config to run the swagger docs on a different port if required. 

That way we can proxy users request via different subdomains to the correct end point. 

Eg. 
api.example.com -> port 8080
docs.example.com -> port 8090
