### ISSUE TITLE
Error on build M1 Metal

### ISSUE THREAD

**Issue by juanfpo96** [mudler/LocalAI#626]
**LocalAI version:**
commit 618fd1d41730ab03f7ac40e2457ea29709756b1f

**Environment, CPU architecture, OS, and Version:**
Macbook Pro M1 Pro 16GB, macOS 12.6

**Describe the bug**
Failure on build

**To Reproduce**
make BUILD_TYPE=metal build

**Expected behavior**
build finished OK

**Logs**
```
In file included from gobert.cpp:6:
go-bert/bert.cpp/bert.cpp:692:74: warning: format specifies type 'int' but the argument has type 'unsigned long' [-Wformat]
# github.com/go-skynet/go-ggml-transformers.cpp
replit.cpp:65:50: warning: format specifies type 'int' but the argument has type 'std::__vector_base<unsigned long, std::allocator<unsigned long>>::value_type' (aka 'unsigned long') [-Wformat]
# github.com/go-skynet/LocalAI/pkg/model
pkg/model/initializers.go:164:86: undefined: gpt4all.SetLibrarySearchPath
make: *** [build] Error 1
```

**Additional context**
I have pulled latest changes, it was working previously in a revision from last week.

**Comment by mudler** [comment]
did you run `make clean` first?

**Comment by drpaneas** [comment]
I do not have M1, but I do have a regular x86_64 Macbook Pro from 2020 and I just cloned the project and I did:

```
make prepare
make build
```

and it failed:

```
[....]
  "_whisper_token_translate", referenced from:
      __cgo_6d775385d461_Cfunc_whisper_token_translate in 000035.o
     (maybe you meant: __cgo_6d775385d461_Cfunc_whisper_token_translate)
  "_whisper_tokenize", referenced from:
      __cgo_6d775385d461_Cfunc_whisper_tokenize in 000035.o
     (maybe you meant: __cgo_6d775385d461_Cfunc_whisper_tokenize)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [build] Error 1
```

If this is not relevant to this issue, please ignore it.

**Comment by Aisuko** [comment]
> 

Make sure you run `make clean` to remove all the .cpp, and .c files and rebuild them. I assume that maybe some files cannot be recognized in the header file. https://stackoverflow.com/questions/49453582/symbols-not-found-for-architecture-x86-64-mac-os-10-13-3

**Comment by drpaneas** [comment]
I tried that and didn't fix the issue. Basically you need to devenv for C and C++, and if you don't then you end up with GH issues like that. I guess building inside a container (mounting the local source code, so it can export the binary) would be better approach in terms of compatibility.

**Comment by Aisuko** [comment]
> I tried that and didn't fix the issue. Basically you need to devenv for C and C++, and if you don't then you end up with GH issues like that. I guess building inside a container (mounting the local source code, so it can export the binary) would be better approach in terms of compatibility.

This is a good idea, I have tried it before but the container environment has some weird issues with the arm container environment, here is an issue https://github.com/devcontainers/images/issues/566

**Comment by ChristianWeyer** [comment]
> I tried that and didn't fix the issue. Basically you need to devenv for C and C++, and if you don't then you end up with GH issues like that. I guess building inside a container (mounting the local source code, so it can export the binary) would be better approach in terms of compatibility.

Did you ever solve this @drpaneas ?

**Comment by drpaneas** [comment]
@ChristianWeyer honestly I don't remember. I think I did, but it's been quite awhile and I don't remember what and how :/
