### ISSUE TITLE
feat: support chatglm

### ISSUE THREAD

**Issue by luoweb** [mudler/LocalAI#754]
ChatGLM project like llama.cpp https://github.com/li-plus/chatglm.cpp

**Comment by mudler** [comment]
good catch, def. we can add it!

**Comment by Aisuko** [comment]
According to the chatGLM project README.md.  I assume it can be compatible by the C++ backend. https://github.com/li-plus/chatglm.cpp#features

**Comment by fishfree** [comment]
I have test ChatGLM. It still does not work.

**Comment by BackMountainDevil** [comment]
@fishfree which version you test chatglm? 2 or 3? In 3, they said the have designed a new prompt format.

**Comment by szsteven008** [comment]
can access the gRPC interface service of chatglm using external-grpc-backends. Here are a example：https://github.com/szsteven008/chatglm.cpp/tree/main/examples/server

**Comment by mudler** [comment]
Closing as this is now both supported by the llama.cpp and transformers backends.
