### ISSUE TITLE
Reload a model in VRAM

### ISSUE THREAD

**Issue by gregoryca** [mudler/LocalAI#892]
**Is your feature request related to a problem? Please describe.**
Currently when using GPU offloading, i offload 35 (the max layers with 8gb vram) layers to have a speedy generation.
If i have for example one flow that uses a vicuna model, and another one that uses gpt-4all-j, i get the following error when one of the models already have been loaded in to the VRAM of the GPU

2:58PM DBG GRPC(vicuna.bin-127.0.0.1:36471): stderr CUDA error 2 at /build/go-llama/llama.cpp/ggml-cuda.cu:5500: out of memory

**Describe the solution you'd like**
Could it be possible to clear the VRAM when a model is idle for longer than 5 or 10 seconds, so the VRAM is cleared to be loaded by another model ? The amount of time could be a variable so that we can tweak different flows with different models

**Additional context**
I have tried to use less layers, but that also makes the generation slower. It was possible to use two models at the same time with a perfomance penalty, but i rather have the option to be able to clear the vram on idle or specify when the vram should be cleared (for example reloading the page where the chatbot/api/front-end runs)

**Comment by mudler** [comment]
JFYI meanwhile in the direction of this #925 was merged which allows to keep "one" backend loaded only - this allows to use a system which is not capable to running parallel models by just stopping the unused backends.

**Comment by ER-EPR** [comment]
> Other options: Check available VRAM before loading a model. If the model is larger than the available memory and another model is already loaded, unload models as needed to free up VRAM and allow the new model to be loaded. In my case, I'd like to keep the model in memory indefinitely until I select another model.

is this auto clear and replace vram function implemented now? I'm still experiencing llama.cpp can't load new models when VRAM is occupied by already loaded model kind of error. Do I need to write some parameters in the config file or envs?

**Comment by naifmeh** [comment]
@ER-EPR
In case you're still stuck with this, I believe that you could set the LOCALAI_SINGLE_ACTIVE_BACKEND environment variable to true and it will unload any existing model before loading a new one.
