### ISSUE TITLE
webui: install wizard/model gallery installer

### ISSUE THREAD

**Issue by mudler** [mudler/LocalAI#918]
Would be super-awesome to have a small wizard, that might be disabled by default along - to setup an instance by installing few models from the gallery. Ideally would be cool to have as well a "lite" management UX for the gallery too. 

It does not have to be necessary part of LocalAI, however, there should be an easy way to install models directly from the browser and/or CLI

**Comment by Jirubizu** [comment]
I am currently working on a project that will allow users to just potentially run a webui along side their api which will expose an admin panel to install new models and view job states. Development is one in the following repo, but I would like to note this is still a heavily WIP project

https://github.com/Jirubizu/localai-admin

**Comment by mudler** [comment]
this is done now. We have a follow-up card to track enhancements #2156
